// AUTO-GENERATED — do not edit by hand.
// Regenerate via: CLOUD_USER=… CLOUD_PASS=… node .dev-server/fetch-alarm-codes.mjs
// Source: Hoymiles cloud `monitor/api/0/option/mwc` dictionary, fetched per `language` header.
// Languages whose name equals the English baseline are omitted (en-fallback covers them).
import type { AlarmTranslation } from "./alarmCodes.js";

/** Native micro-inverter warning codes with cloud-provided localizations. */
export const MWC_ALARM_CODES: Record<number, AlarmTranslation> = {
	121: {
		en: "Over temperature protection",
		de: "Übertemperaturschutz",
		ru: "Защита от перегрева",
		pt: "Proteção contra superaquecimento",
		nl: "Bescherming tegen te hoge temperatuur",
		fr: "Protection contre la surchauffe",
		it: "Protezione da sovratemperatura",
		es: "Protección contra exceso de temperatura",
		pl: "Zabezpieczenie przed przekroczeniem temperatury",
		"zh-cn": "过温保护",
	},
	122: {
		en: "Locked by anti-theft lock",
		de: "Durch Diebstahlsicherung gesperrt",
		ru: "Заблокировано противокражным замком",
		pt: "Bloqueado por trava antifurto",
		nl: "Vergrendeld via antidiefstalvergrendeling",
		fr: "Verrouillé par le verrou antivol",
		it: "Bloccato tramite blocco antifurto",
		es: "Bloqueo por Cerradura Antirrobo",
		pl: "Zablokowany przez blokadę zapobiegającą kradzieży",
		"zh-cn": "防盗锁死",
	},
	123: {
		en: "Standby mode enabled by remote control",
		de: "Standby-Modus per Fernbedienung aktiviert",
		ru: "Дистанционное включение режима ожидания",
		pt: "Modo de espera ativado por controle remoto",
		nl: "Stand-bymodus ingeschakeld met afstandsbediening",
		fr: "Mode veille activé par télécommande",
		it: "Modalità standby attivata tramite controllo remoto",
		es: "Modo de espera activado por control remoto",
		pl: "Tryb czuwania uruchamiany pilotem",
		"zh-cn": "远程待机",
	},
	125: {
		en: "Grid configuration parameter error",
		de: "Parameterfehler bei der Konfiguration des Elektrizitätsnetzes",
		ru: "Ошибка параметра конфигурации электросети",
		pt: "Erro de parâmetro de configuração da rede",
		nl: "Fout in netconfiguratieparameter",
		fr: "Erreur de paramètre de configuration du réseau",
		it: "Errore parametri di configurazione della rete",
		es: "Error en parámetro de configuración de red",
		pl: "Błąd parametru konfiguracji sieci",
		"zh-cn": "并网配置文件参数错误",
	},
	127: {
		en: "Firmware error",
		de: "Firmwarefehler",
		ru: "Ошибка встроенного ПО",
		pt: "Erro de firmware",
		nl: "Firmwarefout",
		fr: "Erreur du micrologiciel",
		it: "Errore firmware",
		es: "Error de firmware",
		pl: "Błąd oprogramowania układowego",
		"zh-cn": "固件错误",
	},
	128: {
		en: "Hardware configuration information error",
		de: "Fehler in der Hardware-Konfigurationsinformation",
		ru: "Ошибка сведений о конфигурации аппаратной части",
		pt: "Erro nas informações de configuração do hardware",
		nl: "Gegevensfout hardwareconfiguratie",
		fr: "Erreur d’informations de configuration matérielle",
		it: "Errore nelle informazioni di configurazione hardware",
		es: "Error de información de configuración del hardware",
		pl: "Błąd informacji o konfiguracji sprzętu",
		"zh-cn": "硬件配置信息错误",
	},
	129: {
		en: "Abnormal bias",
		de: "Abnormaler Trend",
		ru: "Аномальное смещение",
		pt: "Desvio anormal",
		nl: "Abnormale vertekening",
		fr: "Biais anormal",
		it: "Bias anomalo",
		es: "Polarización anormal",
		pl: "Niepoprawność wskazań",
		"zh-cn": "偏置异常",
	},
	141: {
		en: "Grid overvoltage",
		de: "Netzüberspannung",
		ru: "Перенапряжение электросети",
		pt: "Sobretensão de rede",
		nl: "Netoverspanning",
		fr: "Surtension du réseau",
		it: "Sovratensione di rete",
		es: "Sobretensión en la red",
		pl: "Nadnapięcie w sieci",
		"zh-cn": "电网过压",
	},
	142: {
		en: "Grid overvoltage (10 min mean value)",
		de: "Netzüberspannung (10-min. Mittelwert)",
		ru: "Перенапряжение электросети (среднее значение за 10 мин)",
		pt: "Sobretensão de rede (valor médio 10 min)",
		nl: "Netoverspanning (10 min. gemiddelde waarde)",
		fr: "Surtension du réseau (valeur moyenne sur 10 minutes)",
		it: "Sovratensione di rete (valore medio 10 min)",
		es: "Sobretensión de red (valor medio de 10 minutos)",
		pl: "Nadnapięcie sieci (wartość średnia, 10 min)",
		"zh-cn": "电网10分钟平均值过压",
	},
	143: {
		en: "Grid undervoltage",
		de: "Netzunterspannung",
		ru: "Пониженное напряжение электросети",
		pt: "Subtensão de rede",
		nl: "Netonderspanning",
		fr: "Sous-tension du réseau",
		it: "Sottotensione di rete",
		es: "Subtensión en la red",
		pl: "Podnapięcie w sieci",
		"zh-cn": "电网欠压",
	},
	144: {
		en: "Grid overfrequency",
		de: "Netzüberfrequenz",
		ru: "Повышенная частота электросети",
		pt: "Sobrefrequência de rede",
		nl: "Netoverfrequentie",
		fr: "Surfréquence du réseau",
		it: "Sovrafrequenza di rete",
		es: "Sobrefrecuencia de la red",
		pl: "Nadczęstotliwość w sieci",
		"zh-cn": "电网过频",
	},
	145: {
		en: "Grid underfrequency",
		de: "Netzunterfrequenz",
		ru: "Пониженная частота электросети",
		pt: "Subfrequência de rede",
		nl: "Netonderfrequentie",
		fr: "Sous-fréquence du réseau",
		it: "Sottofrequenza di rete",
		es: "Subfrecuencia de la red",
		pl: "Podczęstotliwość w sieci",
		"zh-cn": "电网欠频",
	},
	146: {
		en: "High RoCoF",
		de: "Hohe RoCoF",
		ru: "Высокая скорость изменения частоты",
		pt: "RoCoF elevada",
		nl: "Hoge RoCoF",
		fr: "RoCoF élevé",
		it: "RoCoF elevata",
		es: "Tasa de Cambio de Frecuencia (RoCoF) Alta",
		pl: "Wysoki RoCoF",
		"zh-cn": "电网频率变化率过大",
	},
	147: {
		en: "No voltage on grid port",
		de: "Keine Spannung am Netzanschluss",
		ru: "Отсутствует напряжение на разъёме сети",
		pt: "Sem tensão na porta da rede",
		nl: "Geen spanning op netpoort",
		fr: "Pas de tension sur le port du réseau",
		it: "Nessuna tensione sulla porta di rete",
		es: "No hay voltaje en el puerto de red",
		pl: "Brak napięcia w porcie sieci",
		"zh-cn": "电网端口无输入",
	},
	148: {
		en: "Grid disconnection",
		de: "Netztrennung",
		ru: "Отключение от электросети",
		pt: "Desconexão da rede",
		nl: "Netontkoppeling",
		fr: "Déconnexion du réseau",
		it: "Disconnessione dalla rete",
		es: "Desconexión de la red",
		pl: "Odłączanie sieci",
		"zh-cn": "并网线路断路",
	},
	149: {
		en: "Island detected",
		de: "Inselbetrieb festgestellt",
		ru: "Обнаружен вывод на изолированную работу",
		pt: "Ilha detectada",
		nl: "Eiland gedetecteerd",
		fr: "Îlotage détecté",
		it: "Isola rilevata",
		es: "Aislamiento (Isla) detectado",
		pl: "Wykryto wyspę",
		"zh-cn": "孤岛",
	},
	151: {
		en: "Severe grid wave distortion",
		de: "Starke Netzwellenverzerrung",
		ru: "Сильное искажение формы волны в электросети",
		pt: "Distorção grave de onda de rede",
		nl: "Ernstige netgolfvervorming",
		fr: "Forte distorsion des ondes du réseau",
		it: "Grave distorsione dell'onda della rete",
		es: "Distorsión severa de la onda de red",
		pl: "Znaczące zniekształcenie fali sieci",
		"zh-cn": "电网波形畸变严重",
	},
	181: {
		en: "Abnormal insulation impedance",
		de: "Abnormale Isolationsimpedanz",
		ru: "Отклонение полного сопротивления изоляции",
		pt: "Impedância de isolamento anormal",
		nl: "Abnormale isolatie-impedantie",
		fr: "Impédance d’isolement anormale",
		it: "Impedenza di isolamento anomala",
		es: "Impedancia de aislamiento anormal",
		pl: "Nieprawidłowa impedancja izolacji",
		"zh-cn": "绝缘阻抗异常",
	},
	183: {
		en: "Abnormal Relay",
		de: "Anormales Relais",
		ru: "Ошибка реле",
		pt: "Relé anormal",
		nl: "Abnormale relais",
		fr: "Relais anormal",
		it: "Anomalia relè",
		es: "Relé anormal",
		pl: "Nieprawidłowy przekaźnik",
		"zh-cn": "继电器异常",
	},
	184: {
		en: "Abnormal Input Paralleling Wiring",
		de: "Anormale Eingangs-Parallelverkabelung",
		ru: "Ошибка параллельного подключения на входе",
		pt: "Fiação de entrada em paralelo anormal",
		nl: "Abnormale parallelle bedradingsinvoer",
		fr: "Anomalie de câblage de mise en parallèle des entrées",
		it: "Anomalia ingresso cablaggio in parallelo",
		es: "Cableado en paralelo de entrada anormal",
		pl: "Nieprawidłowe okablowanie równoległego wejścia",
		"zh-cn": "输入并联异常",
	},
	205: {
		en: "MPPT-A input overvoltage",
		de: "Eingangsüberspannung bei MPPT-A",
		ru: "Перенапряжение на входе MPPT-A",
		pt: "Sobretensão de entrada MPPT-A",
		nl: "Overspanning MPPT-A-ingang",
		fr: "Surtension de l’entrée MPPT-A",
		it: "Sovratensione ingresso MPPT-A",
		es: "Sobretensión de entrada MPPT-A",
		pl: "Nadnapięcie wejścia MPPT-A",
		"zh-cn": "MPPT-A 输入过压",
	},
	206: {
		en: "MPPT-B input overvoltage",
		de: "Eingangsüberspannung bei MPPT-B",
		ru: "Перенапряжение на входе MPPT-B",
		pt: "Sobretensão de entrada MPPT-B",
		nl: "Overspanning MPPT-B-ingang",
		fr: "Surtension de l’entrée MPPT-B",
		it: "Sovratensione ingresso MPPT-B",
		es: "Sobretensión de entrada MPPT-B",
		pl: "Nadnapięcie wejścia MPPT-B",
		"zh-cn": "MPPT-B 输入过压",
	},
	207: {
		en: "MPPT-A input undervoltage",
		de: "Eingangsunterspannung bei MPPT-A",
		ru: "Пониженное напряжение на входе MPPT-A",
		pt: "Subtensão de entrada MPPT-A",
		nl: "Onderspanning MPPT-A-ingang",
		fr: "Sous-tension de l’entrée MPPT-A",
		it: "Sottotensione ingresso MPPT-A",
		es: "Subtensión de entrada MPPT-A",
		pl: "Podnapięcie wejścia MPPT-A",
		"zh-cn": "MPPT-A 输入欠压",
	},
	208: {
		en: "MPPT-B input undervoltage",
		de: "Eingangsunterspannung bei MPPT-B",
		ru: "Пониженное напряжение на входе MPPT-B",
		pt: "Subtensão de entrada MPPT-B",
		nl: "Onderspanning MPPT-B-ingang",
		fr: "Sous-tension de l’entrée MPPT-B",
		it: "Sottotensione ingresso MPPT-B",
		es: "Subtensión de entrada MPPT-B",
		pl: "Podnapięcie wejścia MPPT-B",
		"zh-cn": "MPPT-B 输入欠压",
	},
	209: {
		en: "PV1 no input",
		de: "PV1 ohne Eingang",
		ru: "Отсутствует напряжение на входе ФЭ панели 1",
		pt: "Sem entrada FV1",
		nl: "Geen invoer voor PV1",
		fr: "Aucune entrée PV1",
		it: "Nessun ingresso FV1",
		es: "Sin entrada en el puerto FV1",
		pl: "Brak wejścia PV1",
		"zh-cn": "PV1端口无输入",
	},
	210: {
		en: "PV2 no input",
		de: "PV2 ohne Eingang",
		ru: "Отсутствует напряжение на входе ФЭ панели 2",
		pt: "Sem entrada FV2",
		nl: "Geen invoer voor PV2",
		fr: "Aucune entrée PV2",
		it: "Nessun ingresso FV2",
		es: "Sin entrada en el puerto FV2",
		pl: "Brak wejścia PV2",
		"zh-cn": "PV2端口无输入",
	},
	211: {
		en: "PV3 no input",
		de: "PV3 ohne Eingang",
		ru: "Отсутствует напряжение на входе ФЭ панели 3",
		pt: "Sem entrada FV3",
		nl: "Geen invoer voor PV3",
		fr: "Aucune entrée PV3",
		it: "Nessun ingresso FV3",
		es: "Sin entrada en el puerto FV3",
		pl: "Brak wejścia PV3",
		"zh-cn": "PV3端口无输入",
	},
	212: {
		en: "PV4 no input",
		de: "PV4 ohne Eingang",
		ru: "Отсутствует напряжение на входе ФЭ панели 4",
		pt: "Sem entrada FV4",
		nl: "Geen invoer voor PV4",
		fr: "Aucune entrée PV4",
		it: "Nessun ingresso FV4",
		es: "Sin entrada en el puerto FV4",
		pl: "Brak wejścia PV4",
		"zh-cn": "PV4端口无输入",
	},
	213: {
		en: "PV1 & PV2 abnormal wiring",
		de: "Verdrahtungsfehler bei PV1 und PV2",
		ru: "Неисправность проводки ФЭ панелей 1 и 2",
		pt: "Cabeamento anormal FV1 e FV2",
		nl: "Abnormale bedrading PV1 en PV2",
		fr: "Câblage anormal PV1 & PV2",
		it: "Cablaggio anomalo FV1 e FV2",
		es: "Cableado anormal de FV1 y FV2",
		pl: "Nieprawidłowe okablowanie PV1 i PV2",
		"zh-cn": "PV-1&PV-2端口接线异常",
	},
	214: {
		en: "PV3 & PV4 abnormal wiring",
		de: "Verdrahtungsfehler bei PV3 und PV4",
		ru: "Неисправность проводки ФЭ панелей 3 и 4",
		pt: "Cabeamento anormal FV3 e FV4",
		nl: "Abnormale bedrading PV3 en PV4",
		fr: "Câblage anormal PV3 & PV4",
		it: "Cablaggio anomalo FV3 e FV4",
		es: "Cableado anormal de FV3 y FV4",
		pl: "Nieprawidłowe okablowanie PV3 i PV4",
		"zh-cn": "PV-3&PV-4端口接线异常",
	},
	215: {
		en: "PV1 input overvoltage",
		de: "Eingangsüberspannung bei PV1",
		ru: "Перенапряжение на входе ФЭ панели 1",
		pt: "Sobretensão de entrada FV1",
		nl: "Overspanning PV1-ingang",
		fr: "Surtension de l’entrée PV1",
		it: "Sovratensione ingresso FV1",
		es: "Sobretensión de entrada en FV1",
		pl: "Nadnapięcie wejściowe PV1",
		"zh-cn": "PV1输入过压",
	},
	216: {
		en: "PV1 input undervoltage",
		de: "Eingangsunterspannung bei PV1",
		ru: "Пониженное напряжение на входе ФЭ панели 1",
		pt: "Subtensão de entrada FV1",
		nl: "Onderspanning PV1-ingang",
		fr: "Sous-tension de l’entrée PV1",
		it: "Sottotensione ingresso FV1",
		es: "Subtensión de entrada en FV1",
		pl: "Podnapięcie wejściowe PV1",
		"zh-cn": "PV1输入欠压",
	},
	217: {
		en: "PV2 input overvoltage",
		de: "Eingangsüberspannung bei PV2",
		ru: "Перенапряжение на входе ФЭ панели 2",
		pt: "Sobretensão de entrada FV2",
		nl: "Overspanning PV2-ingang",
		fr: "Surtension de l’entrée PV2",
		it: "Sovratensione ingresso FV2",
		es: "Sobretensión de entrada en FV2",
		pl: "Nadnapięcie wejściowe PV2",
		"zh-cn": "PV2输入过压",
	},
	218: {
		en: "PV2 input undervoltage",
		de: "Eingangsunterspannung bei PV2",
		ru: "Пониженное напряжение на входе ФЭ панели 2",
		pt: "Subtensão de entrada FV2",
		nl: "Onderspanning PV2-ingang",
		fr: "Sous-tension de l’entrée PV2",
		it: "Sottotensione ingresso FV2",
		es: "Subtensión de entrada en FV2",
		pl: "Podnapięcie wejściowe PV2",
		"zh-cn": "PV2输入欠压",
	},
	219: {
		en: "PV3 input overvoltage",
		de: "Eingangsüberspannung bei PV3",
		ru: "Перенапряжение на входе ФЭ панели 3",
		pt: "Sobretensão de entrada FV3",
		nl: "Overspanning PV3-ingang",
		fr: "Surtension de l’entrée PV3",
		it: "Sovratensione ingresso FV3",
		es: "Sobretensión de entrada en FV3",
		pl: "Nadnapięcie wejściowe PV3",
		"zh-cn": "PV3输入过压",
	},
	220: {
		en: "PV3 input undervoltage",
		de: "Eingangsunterspannung bei PV3",
		ru: "Пониженное напряжение на входе ФЭ панели 3",
		pt: "Subtensão de entrada FV3",
		nl: "Onderspanning PV3-ingang",
		fr: "Sous-tension de l’entrée PV3",
		it: "Sottotensione ingresso FV3",
		es: "Subtensión de entrada en FV3",
		pl: "Podnapięcie wejściowe PV3",
		"zh-cn": "PV3输入欠压",
	},
	221: {
		en: "PV4 input overvoltage",
		de: "Eingangsüberspannung bei PV4",
		ru: "Перенапряжение на входе ФЭ панели 4",
		pt: "Sobretensão de entrada FV4",
		nl: "Overspanning PV4-ingang",
		fr: "Surtension de l’entrée PV4",
		it: "Sovratensione ingresso FV4",
		es: "Sobretensión de entrada en FV4",
		pl: "Nadnapięcie wejściowe PV4",
		"zh-cn": "PV4输入过压",
	},
	222: {
		en: "PV4 input undervoltage",
		de: "Eingangsunterspannung bei PV4",
		ru: "Пониженное напряжение на входе ФЭ панели 4",
		pt: "Subtensão de entrada FV4",
		nl: "Onderspanning PV4-ingang",
		fr: "Sous-tension de l’entrée PV4",
		it: "Sottotensione ingresso FV4",
		es: "Subtensión de entrada en FV4",
		pl: "Podnapięcie wejściowe PV4",
		"zh-cn": "PV4输入欠压",
	},
	229: {
		en: "Relay inner side Overvoltage",
		de: "Überspannung an Relais-Innenseite",
		ru: "Перенапряжение со стороны внутреннего соединения реле",
		pt: "Sobretensão no lado interno do relé",
		nl: "Relais binnenzijde overspanning",
		fr: "Surtension du côté intérieur du relais",
		it: "Sovratensione lato interno relè",
		es: "Sobretensión en el lado interior del relé",
		pl: "Przepięcie strony wewnętrznej przekaźnika",
		"zh-cn": "继电器内侧电压过压",
	},
	231: {
		en: "PV1 Arcing Fault",
		de: "PV1 Störlichtbogen",
		ru: "Дуговое замыкание ФЭ панели 1",
		pt: "Falha de arco PV1",
		nl: "PV1 Vlamboogstoring",
		fr: "PV1 Défaut d’arc",
		it: "Guasto causato da un arco elettrico FV1",
		es: "Falla de arco FV1",
		pl: "Usterka łuku elektrycznego PV1",
		"zh-cn": "PV1拉弧故障",
	},
	232: {
		en: "PV2 Arcing Fault",
		de: "PV2 Störlichtbogen",
		ru: "Дуговое замыкание ФЭ панели 2",
		pt: "Falha de arco PV2",
		nl: "PV2 Vlamboogstoring",
		fr: "PV2 Défaut d’arc",
		it: "Guasto causato da un arco elettrico FV2",
		es: "Falla de arco FV2",
		pl: "Usterka łuku elektrycznego PV2",
		"zh-cn": "PV2拉弧故障",
	},
	233: {
		en: "PV3 Arcing Fault",
		de: "PV3 Störlichtbogen",
		ru: "Дуговое замыкание ФЭ панели 3",
		pt: "Falha de arco PV3",
		nl: "PV3 Vlamboogstoring",
		fr: "PV3 Défaut d’arc",
		it: "Guasto causato da un arco elettrico FV3",
		es: "Falla de arco FV3",
		pl: "Usterka łuku elektrycznego PV3",
		"zh-cn": "PV3拉弧故障",
	},
	234: {
		en: "PV4 Arcing Fault",
		de: "PV4 Störlichtbogen",
		ru: "Дуговое замыкание ФЭ панели 4",
		pt: "Falha de arco PV4",
		nl: "PV4 Vlamboogstoring",
		fr: "PV4 Défaut d’arc",
		it: "Guasto causato da un arco elettrico FV4",
		es: "Falla de arco FV4",
		pl: "Usterka łuku elektrycznego PV4",
		"zh-cn": "PV4拉弧故障",
	},
	301: {
		en: "Hardware error Code 301",
		de: "Hardwarefehlercode 301",
		ru: "Код аппаратной ошибки 301",
		pt: "Código de erro de hardware 301",
		nl: "Hardwarefoutcode 301",
		fr: "Code d’erreur matériel 301",
		it: "Errore hardware Codice 301",
		es: "Código de Error de Hardware 301",
		pl: "Kod błędu sprzętowego 301",
		"zh-cn": "硬件错误码301",
	},
	302: {
		en: "Hardware error Code 302",
		de: "Hardwarefehlercode 302",
		ru: "Код аппаратной ошибки 302",
		pt: "Código de erro de hardware 302",
		nl: "Hardwarefoutcode 302",
		fr: "Code d’erreur matériel 302",
		it: "Errore hardware Codice 302",
		es: "Código de Error de Hardware 302",
		pl: "Kod błędu sprzętowego 302",
		"zh-cn": "硬件错误码302",
	},
	303: {
		en: "Hardware error Code 303",
		de: "Hardwarefehlercode 303",
		ru: "Код аппаратной ошибки 303",
		pt: "Código de erro de hardware 303",
		nl: "Hardwarefoutcode 303",
		fr: "Code d’erreur matériel 303",
		it: "Errore hardware Codice 303",
		es: "Código de Error de Hardware 303",
		pl: "Kod błędu sprzętowego 303",
		"zh-cn": "硬件错误码303",
	},
	304: {
		en: "Hardware error Code 304",
		de: "Hardwarefehlercode 304",
		ru: "Код аппаратной ошибки 304",
		pt: "Código de erro de hardware 304",
		nl: "Hardwarefoutcode 304",
		fr: "Code d’erreur matériel 304",
		it: "Errore hardware Codice 304",
		es: "Código de Error de Hardware 304",
		pl: "Kod błędu sprzętowego 304",
		"zh-cn": "硬件错误码304",
	},
	305: {
		en: "Hardware error Code 305",
		de: "Hardwarefehlercode 305",
		ru: "Код аппаратной ошибки 305",
		pt: "Código de erro de hardware 305",
		nl: "Hardwarefoutcode 305",
		fr: "Code d’erreur matériel 305",
		it: "Errore hardware Codice 305",
		es: "Código de Error de Hardware 305",
		pl: "Kod błędu sprzętowego 305",
		"zh-cn": "硬件错误码305",
	},
	306: {
		en: "Hardware error Code 306",
		de: "Hardwarefehlercode 306",
		ru: "Код аппаратной ошибки 306",
		pt: "Código de erro de hardware 306",
		nl: "Hardwarefoutcode 306",
		fr: "Code d’erreur matériel 306",
		it: "Errore hardware Codice 306",
		es: "Código de Error de Hardware 306",
		pl: "Kod błędu sprzętowego 306",
		"zh-cn": "硬件错误码306",
	},
	307: {
		en: "Hardware error Code 307",
		de: "Hardwarefehlercode 307",
		ru: "Код аппаратной ошибки 307",
		pt: "Código de erro de hardware 307",
		nl: "Hardwarefoutcode 307",
		fr: "Code d’erreur matériel 307",
		it: "Errore hardware Codice 307",
		es: "Código de Error de Hardware 307",
		pl: "Kod błędu sprzętowego 307",
		"zh-cn": "硬件错误码307",
	},
	308: {
		en: "Hardware error Code 308",
		de: "Hardwarefehlercode 308",
		ru: "Код аппаратной ошибки 308",
		pt: "Código de erro de hardware 308",
		nl: "Hardwarefoutcode 308",
		fr: "Code d’erreur matériel 308",
		it: "Errore hardware Codice 308",
		es: "Código de Error de Hardware 308",
		pl: "Kod błędu sprzętowego 308",
		"zh-cn": "硬件错误码308",
	},
	309: {
		en: "Hardware error Code 309",
		de: "Hardwarefehlercode 309",
		ru: "Код аппаратной ошибки 309",
		pt: "Código de erro de hardware 309",
		nl: "Hardwarefoutcode 309",
		fr: "Code d’erreur matériel 309",
		it: "Errore hardware Codice 309",
		es: "Código de Error de Hardware 309",
		pl: "Kod błędu sprzętowego 309",
		"zh-cn": "硬件错误码309",
	},
	310: {
		en: "Hardware error Code 310",
		de: "Hardwarefehlercode 310",
		ru: "Код аппаратной ошибки 310",
		pt: "Código de erro de hardware 310",
		nl: "Hardwarefoutcode 310",
		fr: "Code d’erreur matériel 310",
		it: "Errore hardware Codice 310",
		es: "Código de Error de Hardware 310",
		pl: "Kod błędu sprzętowego 310",
		"zh-cn": "硬件错误码310",
	},
	311: {
		en: "Hardware error Code 311",
		de: "Hardwarefehlercode 311",
		ru: "Код аппаратной ошибки 311",
		pt: "Código de erro de hardware 311",
		nl: "Hardwarefoutcode 311",
		fr: "Code d’erreur matériel 311",
		it: "Errore hardware Codice 311",
		es: "Código de Error de Hardware 311",
		pl: "Kod błędu sprzętowego 311",
		"zh-cn": "硬件错误码311",
	},
	312: {
		en: "Hardware error Code 312",
		de: "Hardwarefehlercode 312",
		ru: "Код аппаратной ошибки 312",
		pt: "Código de erro de hardware 312",
		nl: "Hardwarefoutcode 312",
		fr: "Code d’erreur matériel 312",
		it: "Errore hardware Codice 312",
		es: "Código de Error de Hardware 312",
		pl: "Kod błędu sprzętowego 312",
		"zh-cn": "硬件错误码312",
	},
	313: {
		en: "Hardware error Code 313",
		de: "Hardwarefehlercode 313",
		ru: "Код аппаратной ошибки 313",
		pt: "Código de erro de hardware 313",
		nl: "Hardwarefoutcode 313",
		fr: "Code d’erreur matériel 313",
		it: "Errore hardware Codice 313",
		es: "Código de Error de Hardware 313",
		pl: "Kod błędu sprzętowego 313",
		"zh-cn": "硬件错误码313",
	},
	314: {
		en: "Hardware error Code 314",
		de: "Hardwarefehlercode 314",
		ru: "Код аппаратной ошибки 314",
		pt: "Código de erro de hardware 314",
		nl: "Hardwarefoutcode 314",
		fr: "Code d’erreur matériel 314",
		it: "Errore hardware Codice 314",
		es: "Código de Error de Hardware 314",
		pl: "Kod błędu sprzętowego 314",
		"zh-cn": "硬件错误码314",
	},
	316: {
		en: "BOOSTA internal short circuit failure",
		de: "BOOSTA interner Kurzschlussfehler",
		ru: "Внутреннее короткое замыкание BOOSTA",
		pt: "Falha de curto-circuito interno em BOOSTA",
		nl: "BOOSTA interne kortsluitingsstoring",
		fr: "Anomalie de la protection contre les courts-circuits internes BOOSTA",
		it: "Errore cortocircuito interno BOOSTA",
		es: "Falla de cortocircuito interno de BOOSTA",
		pl: "Błąd zwarcia wewnętrznego BOOSTA",
		"zh-cn": "BOOSTA内部短路失效",
	},
	317: {
		en: "BOOSTB internal short circuit failure",
		de: "BOOSTB interner Kurzschlussfehler",
		ru: "Внутреннее короткое замыкание BOOSTB",
		pt: "Falha de curto-circuito interno em BOOSTB",
		nl: "BOOSTB interne kortsluitingsstoring",
		fr: "Anomalie de la protection contre les courts-circuits internes BOOSTB",
		it: "Errore cortocircuito interno BOOSTB",
		es: "Falla de cortocircuito interno de BOOSTB",
		pl: "Błąd zwarcia wewnętrznego BOOSTB",
		"zh-cn": "BOOSTB内部短路失效",
	},
	318: {
		en: "BOOSTA overcurrent protection failure",
		de: "Ausfall des BOOSTA-Überstromschutzes",
		ru: "Неисправность защиты от перегрузки по току BOOSTA",
		pt: "Falha na proteção contra sobrecorrente em BOOSTA",
		nl: "BOOSTA overstroombeveiligingsstoring",
		fr: "Anomalie de la protection contre les surintensités BOOSTA",
		it: "Errore protezione dalle sovracorrenti BOOSTA",
		es: "Falla de protección contra sobrecorriente BOOSTA",
		pl: "Błąd zabezpieczenia przetężeniowego BOOSTA",
		"zh-cn": "BOOSTA过流保护失效",
	},
	319: {
		en: "BOOSTB overcurrent protection failure",
		de: "Ausfall des BOOSTB-Überstromschutzes",
		ru: "Неисправность защиты от перегрузки по току BOOSTB",
		pt: "Falha na proteção contra sobrecorrente em BOOSTB",
		nl: "BOOSTB overstroombeveiligingsstoring",
		fr: "Anomalie de la protection contre les surintensités BOOSTB",
		it: "Errore protezione dalle sovracorrenti BOOSTB",
		es: "Falla de protección contra sobrecorriente BOOSTB",
		pl: "Błąd zabezpieczenia przetężeniowego BOOSTB",
		"zh-cn": "BOOSTB过流保护失效",
	},
	320: {
		en: "BOOSTC internal short circuit failure",
		de: "BOOSTC interner Kurzschlussfehler",
		ru: "Внутреннее короткое замыкание BOOSTC",
		pt: "Falha de curto-circuito interno em BOOSTC",
		nl: "BOOSTC interne kortsluitingsstoring",
		fr: "Anomalie de la protection contre les courts-circuits internes BOOSTC",
		it: "Errore cortocircuito interno BOOSTC",
		es: "Falla de cortocircuito interno de BOOSTC",
		pl: "Błąd zwarcia wewnętrznego BOOSTC",
		"zh-cn": "BOOSTC内部短路失效",
	},
	321: {
		en: "BOOSTD internal short circuit failure",
		de: "BOOSTD interner Kurzschlussfehler",
		ru: "Внутреннее короткое замыкание BOOSTD",
		pt: "Falha de curto-circuito interno em BOOSTD",
		nl: "BOOSTD interne kortsluitingsstoring",
		fr: "Anomalie de la protection contre les courts-circuits internes BOOSTD",
		it: "Errore cortocircuito interno BOOSTD",
		es: "Falla de cortocircuito interno de BOOSTD",
		pl: "Błąd zwarcia wewnętrznego BOOSTD",
		"zh-cn": "BOOSTD内部短路失效",
	},
	322: {
		en: "BOOSTC overcurrent protection failure",
		de: "Ausfall des BOOSTC-Überstromschutzes",
		ru: "Неисправность защиты от перегрузки по току BOOSTC",
		pt: "Falha na proteção contra sobrecorrente em BOOSTC",
		nl: "BOOSTC overstroombeveiligingsstoring",
		fr: "Anomalie de la protection contre les surintensités BOOSTC",
		it: "Errore protezione dalle sovracorrenti BOOSTC",
		es: "Falla de protección contra sobrecorriente BOOSTC",
		pl: "Błąd zabezpieczenia przetężeniowego BOOSTC",
		"zh-cn": "BOOSTC过流保护失效",
	},
	323: {
		en: "BOOSTD overcurrent protection failure",
		de: "Ausfall des BOOSTD-Überstromschutzes",
		ru: "Неисправность защиты от перегрузки по току BOOSTD",
		pt: "Falha na proteção contra sobrecorrente em BOOSTD",
		nl: "BOOSTD overstroombeveiligingsstoring",
		fr: "Anomalie de la protection contre les surintensités BOOSTD",
		it: "Errore protezione dalle sovracorrenti BOOSTD",
		es: "Falla de protección contra sobrecorriente BOOSTD",
		pl: "Błąd zabezpieczenia przetężeniowego BOOSTD",
		"zh-cn": "BOOSTD过流保护失效",
	},
	324: {
		en: "Arcing Lock-Up",
		de: "Sperrlichtbogen",
		ru: "Блокировка из-за дугового замыкания",
		pt: "Bloqueio de arco",
		nl: "Blokkering vlamboogvorming",
		fr: "Verrouillage de l’arc électrique",
		it: "Blocco causato da un arco elettrico",
		es: "Bloqueo de arco",
		pl: "Blokada łuku",
		"zh-cn": "拉弧锁死",
	},
	420: {
		en: "Abnormal master-slave communication",
		de: "Anormale Master-Slave-Kommunikation",
		ru: "Ошибка связи ведущего/ведомого устройства",
		pt: "Comunicação mestre-escravo anormal",
		nl: "Abnormale master-slavecommunicatie",
		fr: "Communication maître-esclave anormale",
		it: "Comunicazione master-slave anomala",
		es: "Comunicación maestro-esclavo anormal",
		pl: "Błąd komunikacji urządzenia głównego i podrzędnego",
		"zh-cn": "主从机通讯异常",
	},
	421: {
		en: "Abnormal master-slave communication",
		de: "Anormale Master-Slave-Kommunikation",
		ru: "Ошибка связи ведущего/ведомого устройства",
		pt: "Comunicação mestre-escravo anormal",
		nl: "Abnormale master-slavecommunicatie",
		fr: "Communication maître-esclave anormale",
		it: "Comunicazione master-slave anomala",
		es: "Comunicación maestro-esclavo anormal",
		pl: "Błąd komunikacji urządzenia głównego i podrzędnego",
		"zh-cn": "主从机通讯异常",
	},
	422: {
		en: "Abnormal master-slave communication",
		de: "Anormale Master-Slave-Kommunikation",
		ru: "Ошибка связи ведущего/ведомого устройства",
		pt: "Comunicação mestre-escravo anormal",
		nl: "Abnormale master-slavecommunicatie",
		fr: "Communication maître-esclave anormale",
		it: "Comunicazione master-slave anomala",
		es: "Comunicación maestro-esclavo anormal",
		pl: "Błąd komunikacji urządzenia głównego i podrzędnego",
		"zh-cn": "主从机通讯异常",
	},
	423: {
		en: "Abnormal master-slave communication",
		de: "Anormale Master-Slave-Kommunikation",
		ru: "Ошибка связи ведущего/ведомого устройства",
		pt: "Comunicação mestre-escravo anormal",
		nl: "Abnormale master-slavecommunicatie",
		fr: "Communication maître-esclave anormale",
		it: "Comunicazione master-slave anomala",
		es: "Comunicación maestro-esclavo anormal",
		pl: "Błąd komunikacji urządzenia głównego i podrzędnego",
		"zh-cn": "主从机通讯异常",
	},
	424: {
		en: "Abnormal master-slave communication",
		de: "Anormale Master-Slave-Kommunikation",
		ru: "Ошибка связи ведущего/ведомого устройства",
		pt: "Comunicação mestre-escravo anormal",
		nl: "Abnormale master-slavecommunicatie",
		fr: "Communication maître-esclave anormale",
		it: "Comunicazione master-slave anomala",
		es: "Comunicación maestro-esclavo anormal",
		pl: "Błąd komunikacji urządzenia głównego i podrzędnego",
		"zh-cn": "主从机通讯异常",
	},
	5051: {
		en: "PV1 input overvoltage/undervoltage",
		de: "Eingangsüberspannung/-unterspannung an PV1",
		pt: "Sobretensão/subtensão de entrada FV1",
		nl: "Overspanning/onderspanning PV1-ingang",
		fr: "Surtension/sous-tension de l’entrée PV1",
		it: "Sovratensione/Sottotensione ingresso FV1",
		es: "Sobretensión / subtensión de entrada FV1",
		pl: "Nad/podnapięcie wejściowe PV1",
		"zh-cn": "PV1 过压或欠压",
	},
	5052: {
		en: "PV2 input overvoltage/undervoltage",
		de: "Eingangsüberspannung/-unterspannung an PV2",
		pt: "Sobretensão/subtensão de entrada FV2",
		nl: "Overspanning/onderspanning PV2-ingang",
		fr: "Surtension/sous-tension de l’entrée PV2",
		it: "Sovratensione/Sottotensione ingresso FV2",
		es: "Sobretensión / subtensión de entrada FV2",
		pl: "Nad/podnapięcie wejściowe PV2",
		"zh-cn": "PV2 过压或欠压",
	},
	5053: {
		en: "PV3 input overvoltage/undervoltage",
		de: "Eingangsüberspannung/-unterspannung an PV3",
		pt: "Sobretensão/subtensão de entrada FV3",
		nl: "Overspanning/onderspanning PV3-ingang",
		fr: "Surtension/sous-tension de l’entrée PV3",
		it: "Sovratensione/Sottotensione ingresso FV3",
		es: "Sobretensión / subtensión de entrada FV3",
		pl: "Nad/podnapięcie wejściowe PV3",
		"zh-cn": "PV3 过压或欠压",
	},
	5054: {
		en: "PV4 input overvoltage/undervoltage",
		de: "Eingangsüberspannung/-unterspannung an PV4",
		pt: "Sobretensão/subtensão de entrada FV4",
		nl: "Overspanning/onderspanning PV4-ingang",
		fr: "Surtension/sous-tension de l’entrée PV4",
		it: "Sovratensione/Sottotensione ingresso FV4",
		es: "Sobretensión / subtensión de entrada FV4",
		pl: "Nad/podnapięcie wejściowe PV4",
		"zh-cn": "PV4 过压或欠压",
	},
	5070: {
		en: "Over temperature protection",
		de: "Übertemperaturschutz",
		ru: "Защита от перегрева",
		pt: "Proteção contra superaquecimento",
		nl: "Bescherming tegen te hoge temperatuur",
		fr: "Protection contre la surchauffe",
		it: "Protezione da sovratemperatura",
		es: "Protección contra exceso de temperatura",
		pl: "Zabezpieczenie przed przekroczeniem temperatury",
		"zh-cn": "过温保护",
	},
	5080: {
		en: "Grid overvoltage/undervoltage",
		de: "Netzüberspannung/-unterspannung",
		pt: "Sobretensão/subtensão de rede",
		nl: "Netoverspanning/-onderspanning",
		fr: "Surtension/sous-tension du réseau",
		it: "Sovratensione/Sottotensione di rete",
		es: "Sobretensión / subtensión de la red",
		pl: "Nad/podnapięcie w sieci",
		"zh-cn": "电网电压过压或欠压",
	},
	5090: {
		en: "Grid overfrequency/underfrequency",
		de: "Netzüberfrequenz/-unterfrequenz",
		pt: "Sobrefrequência/subfrequência de rede",
		nl: "Netoverfrequentie/-onderfrequentie",
		fr: "Surfréquence/sous-fréquence du réseau",
		it: "Sovrafrequenza/Sottofrequenza di rete",
		es: "Sobrefrecuencia / subfrecuencia de la red",
		pl: "Nad/podczęstotliwość w sieci",
		"zh-cn": "电网频率过频或欠频",
	},
	5100: {
		en: "Island detected",
		de: "Inselbetrieb festgestellt",
		ru: "Обнаружен вывод на изолированную работу",
		pt: "Ilha detectada",
		nl: "Eiland gedetecteerd",
		fr: "Îlotage détecté",
		it: "Isola rilevata",
		es: "Aislamiento (Isla) detectado",
		pl: "Wykryto wyspę",
		"zh-cn": "孤岛",
	},
	5110: {
		en: "GFDI failure",
		de: "GFDI-Fehler",
		pt: "Falha GFDI",
		nl: "GFDI-storing",
		fr: "Défaillance GFDI",
		it: "Errore GFDI",
		es: "Falla de GFDI",
		pl: "Usterka GFDI",
		"zh-cn": "GFDI 故障",
	},
	5120: {
		en: "Error Code 12",
		de: "Fehlercode 12",
		pt: "Código de erro 12",
		nl: "Foutcode 12",
		fr: "Code d’erreur 12",
		it: "Codice errore 12",
		es: "Código de error 12",
		pl: "Kod błędu 12",
		"zh-cn": "错误码12",
	},
	5150: {
		en: "Grid overvoltage (10 min mean value)",
		de: "Netzüberspannung (10-min. Mittelwert)",
		ru: "Перенапряжение электросети (среднее значение за 10 мин)",
		pt: "Sobretensão de rede (valor médio 10 min)",
		nl: "Netoverspanning (10 min. gemiddelde waarde)",
		fr: "Surtension du réseau (valeur moyenne sur 10 minutes)",
		it: "Sovratensione di rete (valore medio 10 min)",
		es: "Sobretensión de red (valor medio de 10 minutos)",
		pl: "Nadnapięcie sieci (wartość średnia, 10 min)",
		"zh-cn": "电网10分钟平均值过压",
	},
	5200: {
		en: "Firmware error",
		de: "Firmwarefehler",
		ru: "Ошибка встроенного ПО",
		pt: "Erro de firmware",
		nl: "Firmwarefout",
		fr: "Erreur du micrologiciel",
		it: "Errore firmware",
		es: "Error de firmware",
		pl: "Błąd oprogramowania układowego",
		"zh-cn": "固件错误",
	},
	5511: {
		en: "Error Code 01",
		de: "Fehlercode 01",
		pt: "Código de erro 01",
		nl: "Foutcode 01",
		fr: "Code d’erreur 01",
		it: "Codice errore 01",
		es: "Código de Error 01",
		pl: "Kod błędu 01",
		"zh-cn": "错误码01",
	},
	5512: {
		en: "Error Code 01",
		de: "Fehlercode 01",
		pt: "Código de erro 01",
		nl: "Foutcode 01",
		fr: "Code d’erreur 01",
		it: "Codice errore 01",
		es: "Código de Error 01",
		pl: "Kod błędu 01",
		"zh-cn": "错误码01",
	},
	5513: {
		en: "Error Code 01",
		de: "Fehlercode 01",
		pt: "Código de erro 01",
		nl: "Foutcode 01",
		fr: "Code d’erreur 01",
		it: "Codice errore 01",
		es: "Código de Error 01",
		pl: "Kod błędu 01",
		"zh-cn": "错误码01",
	},
	5514: {
		en: "Error Code 01",
		de: "Fehlercode 01",
		pt: "Código de erro 01",
		nl: "Foutcode 01",
		fr: "Code d’erreur 01",
		it: "Codice errore 01",
		es: "Código de Error 01",
		pl: "Kod błędu 01",
		"zh-cn": "错误码01",
	},
	5520: {
		en: "Error Code 02",
		de: "Fehlercode 02",
		pt: "Código de erro 02",
		nl: "Foutcode 02",
		fr: "Code d’erreur 02",
		it: "Codice errore 02",
		es: "Código de Error 02",
		pl: "Kod błędu 02",
		"zh-cn": "错误码02",
	},
	8310: {
		en: "Shut down by remote control",
		de: "Durch Fernbedienung abgeschaltet",
		pt: "Desligamento por controle remoto",
		nl: "Afsluiten via afstandsbediening",
		fr: "Arrêté par la télécommande",
		it: "Spegnimento via controllo remoto",
		es: "Apagado mediante control remoto",
		pl: "Zamknięty przez zdalne sterowanie",
		"zh-cn": "远程关机",
	},
	8320: {
		en: "Standby mode enabled by remote control",
		de: "Standby-Modus per Fernbedienung aktiviert",
		ru: "Дистанционное включение режима ожидания",
		pt: "Modo de espera ativado por controle remoto",
		nl: "Stand-bymodus ingeschakeld met afstandsbediening",
		fr: "Mode veille activé par télécommande",
		it: "Modalità standby attivata tramite controllo remoto",
		es: "Modo de espera activado por control remoto",
		pl: "Tryb czuwania uruchamiany pilotem",
		"zh-cn": "远程待机",
	},
	9000: {
		en: "Locked by anti-theft lock",
		de: "Durch Diebstahlsicherung gesperrt",
		ru: "Заблокировано противокражным замком",
		pt: "Bloqueado por trava antifurto",
		nl: "Vergrendeld via antidiefstalvergrendeling",
		fr: "Verrouillé par le verrou antivol",
		it: "Bloccato tramite blocco antifurto",
		es: "Bloqueo por Cerradura Antirrobo",
		pl: "Zablokowany przez blokadę zapobiegającą kradzieży",
		"zh-cn": "防盗锁死",
	},
	10120: {
		en: "Abnormal SPI communication",
		de: "Anormale SPI-Kommunikation",
		ru: "Ошибка связи SPI",
		pt: "Comunicação SPI anormal",
		nl: "Abnormale SPI-communicatie",
		fr: "Communication SPI anormale",
		it: "Anomalia comunicazione SPI",
		es: "Comunicación SPI anormal",
		pl: "Nieprawidłowa komunikacja SPI",
		"zh-cn": "SPI 通信异常",
	},
	10121: {
		en: "Over temperature protection",
		de: "Übertemperaturschutz",
		ru: "Защита от перегрева",
		pt: "Proteção contra superaquecimento",
		nl: "Bescherming tegen te hoge temperatuur",
		fr: "Protection contre la surchauffe",
		it: "Protezione da sovratemperatura",
		es: "Protección contra exceso de temperatura",
		pl: "Zabezpieczenie przed przekroczeniem temperatury",
		"zh-cn": "过温保护",
	},
	10122: {
		en: "Locked by anti-theft lock",
		de: "Durch Diebstahlsicherung gesperrt",
		ru: "Заблокировано противокражным замком",
		pt: "Bloqueado por trava antifurto",
		nl: "Vergrendeld via antidiefstalvergrendeling",
		fr: "Verrouillé par le verrou antivol",
		it: "Bloccato tramite blocco antifurto",
		es: "Bloqueo por Cerradura Antirrobo",
		pl: "Zablokowany przez blokadę zapobiegającą kradzieży",
		"zh-cn": "防盗锁死",
	},
	10123: {
		en: "Standby mode enabled by remote control",
		de: "Standby-Modus per Fernbedienung aktiviert",
		ru: "Дистанционное включение режима ожидания",
		pt: "Modo de espera ativado por controle remoto",
		nl: "Stand-bymodus ingeschakeld met afstandsbediening",
		fr: "Mode veille activé par télécommande",
		it: "Modalità standby attivata tramite controllo remoto",
		es: "Modo de espera activado por control remoto",
		pl: "Tryb czuwania uruchamiany pilotem",
		"zh-cn": "远程待机",
	},
	10125: {
		en: "Grid configuration parameter error",
		de: "Parameterfehler bei der Konfiguration des Elektrizitätsnetzes",
		ru: "Ошибка параметра конфигурации электросети",
		pt: "Erro de parâmetro de configuração da rede",
		nl: "Fout in netconfiguratieparameter",
		fr: "Erreur de paramètre de configuration du réseau",
		it: "Errore parametri di configurazione della rete",
		es: "Error en parámetro de configuración de red",
		pl: "Błąd parametru konfiguracji sieci",
		"zh-cn": "并网配置文件参数错误",
	},
	10127: {
		en: "Firmware error",
		de: "Firmwarefehler",
		ru: "Ошибка встроенного ПО",
		pt: "Erro de firmware",
		nl: "Firmwarefout",
		fr: "Erreur du micrologiciel",
		it: "Errore firmware",
		es: "Error de firmware",
		pl: "Błąd oprogramowania układowego",
		"zh-cn": "固件错误",
	},
	10130: {
		en: "Offline",
		ru: "Вне сети",
		pt: "Off-line",
		fr: "Non connecté",
		es: "Fuera de línea",
		pl: "Niepodłączona do sieci",
		"zh-cn": "离线",
	},
	10131: {
		en: "Abnormal Leakage Current",
		de: "Anormaler Leckstrom",
		ru: "Отклонение тока утечки",
		pt: "Corrente de fuga anormal",
		nl: "Abnormale lekstroom",
		fr: "Courant de fuite anormal",
		it: "Anomalia corrente di dispersione",
		es: "Corriente de fuga anormal",
		pl: "Nieprawidłowy prąd upływowy",
		"zh-cn": "漏电流异常",
	},
	10141: {
		en: "Grid overvoltage",
		de: "Netzüberspannung",
		ru: "Перенапряжение электросети",
		pt: "Sobretensão de rede",
		nl: "Netoverspanning",
		fr: "Surtension du réseau",
		it: "Sovratensione di rete",
		es: "Sobretensión en la red",
		pl: "Nadnapięcie w sieci",
		"zh-cn": "电网过压",
	},
	10142: {
		en: "Grid overvoltage (10 min mean value)",
		de: "Netzüberspannung (10-min. Mittelwert)",
		ru: "Перенапряжение электросети (среднее значение за 10 мин)",
		pt: "Sobretensão de rede (valor médio 10 min)",
		nl: "Netoverspanning (10 min. gemiddelde waarde)",
		fr: "Surtension du réseau (valeur moyenne sur 10 minutes)",
		it: "Sovratensione di rete (valore medio 10 min)",
		es: "Sobretensión de red (valor medio de 10 minutos)",
		pl: "Nadnapięcie sieci (wartość średnia, 10 min)",
		"zh-cn": "电网10分钟平均值过压",
	},
	10143: {
		en: "Grid undervoltage",
		de: "Netzunterspannung",
		ru: "Пониженное напряжение электросети",
		pt: "Subtensão de rede",
		nl: "Netonderspanning",
		fr: "Sous-tension du réseau",
		it: "Sottotensione di rete",
		es: "Subtensión en la red",
		pl: "Podnapięcie w sieci",
		"zh-cn": "电网欠压",
	},
	10144: {
		en: "Grid overfrequency",
		de: "Netzüberfrequenz",
		ru: "Повышенная частота электросети",
		pt: "Sobrefrequência de rede",
		nl: "Netoverfrequentie",
		fr: "Surfréquence du réseau",
		it: "Sovrafrequenza di rete",
		es: "Sobrefrecuencia de la red",
		pl: "Nadczęstotliwość w sieci",
		"zh-cn": "电网过频",
	},
	10145: {
		en: "Grid underfrequency",
		de: "Netzunterfrequenz",
		ru: "Пониженная частота электросети",
		pt: "Subfrequência de rede",
		nl: "Netonderfrequentie",
		fr: "Sous-fréquence du réseau",
		it: "Sottofrequenza di rete",
		es: "Subfrecuencia de la red",
		pl: "Podczęstotliwość w sieci",
		"zh-cn": "电网欠频",
	},
	10146: {
		en: "High RoCoF",
		de: "Hohe RoCoF",
		ru: "Высокая скорость изменения частоты",
		pt: "RoCoF elevada",
		nl: "Hoge RoCoF",
		fr: "RoCoF élevé",
		it: "RoCoF elevata",
		es: "Tasa de Cambio de Frecuencia (RoCoF) Alta",
		pl: "Wysoki RoCoF",
		"zh-cn": "电网频率变化率过大",
	},
	10147: {
		en: "No voltage on grid port",
		de: "Keine Spannung am Netzanschluss",
		ru: "Отсутствует напряжение на разъёме сети",
		pt: "Sem tensão na porta da rede",
		nl: "Geen spanning op netpoort",
		fr: "Pas de tension sur le port du réseau",
		it: "Nessuna tensione sulla porta di rete",
		es: "No hay voltaje en el puerto de red",
		pl: "Brak napięcia w porcie sieci",
		"zh-cn": "电网端口无输入",
	},
	10148: {
		en: "Grid disconnection",
		de: "Netztrennung",
		ru: "Отключение от электросети",
		pt: "Desconexão da rede",
		nl: "Netontkoppeling",
		fr: "Déconnexion du réseau",
		it: "Disconnessione dalla rete",
		es: "Desconexión de la red",
		pl: "Odłączanie sieci",
		"zh-cn": "并网线路断路",
	},
	10149: {
		en: "Island detected",
		de: "Inselbetrieb festgestellt",
		ru: "Обнаружен вывод на изолированную работу",
		pt: "Ilha detectada",
		nl: "Eiland gedetecteerd",
		fr: "Îlotage détecté",
		it: "Isola rilevata",
		es: "Aislamiento (Isla) detectado",
		pl: "Wykryto wyspę",
		"zh-cn": "孤岛",
	},
	10152: {
		en: "Abnormal grid phase",
		de: "Anormale Netzphase",
		ru: "Ошибка фазы электросети",
		pt: "Fase de rede anormal",
		nl: "Abnormale netfase",
		fr: "Phase du réseau anormale",
		it: "Fase rete anomala",
		es: "Fase de red anormal",
		pl: "Nieprawidłowa faza sieci",
		"zh-cn": "电网相间相位异常",
	},
	10153: {
		en: "Abnormal Grid Neutral Wiring",
		de: "Anormale Netzneutralleiterverkabelung",
		ru: "Ошибка нейтрального провода электросети",
		pt: "Fiação do neutro da rede anormal",
		nl: "Abnormale net-neutrale bedrading",
		fr: "Câblage neutre du réseau électrique anormal",
		it: "Anomalia conduttore neutro della rete",
		es: "Cableado neutro de red anormal",
		pl: "Nieprawidłowe podłączenie przewodu neutralnego sieci",
		"zh-cn": "电网零线接线异常",
	},
	10183: {
		en: "Abnormal Relay",
		de: "Anormales Relais",
		ru: "Ошибка реле",
		pt: "Relé anormal",
		nl: "Abnormale relais",
		fr: "Relais anormal",
		it: "Anomalia relè",
		es: "Relé anormal",
		pl: "Nieprawidłowy przekaźnik",
		"zh-cn": "继电器异常",
	},
	10200: {
		en: "PV1 Reverse Connection",
		de: "PV1-Anschlusseinstellung stornieren",
		ru: "Неправильная полярность ФЭ панели 1",
		pt: "Conexão inversa PV1",
		nl: "Omgekeerde PV1-aansluiting",
		fr: "Connexion PV1 inversée",
		it: "Inversione collegamento FV1",
		es: "Conexión inversa de FV1",
		pl: "Połączenie odwrotne PV1",
		"zh-cn": "PV1反接",
	},
	10201: {
		en: "PV2 Reverse Connection",
		de: "PV2-Anschlusseinstellung stornieren",
		ru: "Неправильная полярность ФЭ панели 2",
		pt: "Conexão inversa PV2",
		nl: "Omgekeerde PV2-aansluiting",
		fr: "Connexion PV2 inversée",
		it: "Inversione collegamento FV2",
		es: "Conexión inversa de FV2",
		pl: "Połączenie odwrotne PV2",
		"zh-cn": "PV2反接",
	},
	10202: {
		en: "PV3 Reverse Connection",
		de: "PV3-Anschlusseinstellung stornieren",
		ru: "Неправильная полярность ФЭ панели 3",
		pt: "Conexão inversa PV3",
		nl: "Omgekeerde PV3-aansluiting",
		fr: "Connexion PV3 inversée",
		it: "Inversione collegamento FV3",
		es: "Conexión inversa de FV3",
		pl: "Połączenie odwrotne PV3",
		"zh-cn": "PV3反接",
	},
	10203: {
		en: "PV4 Reverse Connection",
		de: "PV4-Anschlusseinstellung stornieren",
		ru: "Неправильная полярность ФЭ панели 4",
		pt: "Conexão inversa PV4",
		nl: "Omgekeerde PV4-aansluiting",
		fr: "Connexion PV4 inversée",
		it: "Inversione collegamento FV4",
		es: "Conexión inversa de FV4",
		pl: "Połączenie odwrotne PV4",
		"zh-cn": "PV4反接",
	},
	10204: {
		en: "PV misconnection",
		de: "PV-Fehlanschluss",
		ru: "Неправильное подключение ФЭ панелей",
		pt: "Conexão fotovoltaica incorreta",
		nl: "PV verkeerde aansluiting",
		fr: "Mauvaise connexion PV",
		it: "Collegamento errato FV",
		es: "Conexión incorrecta FV",
		pl: "Błąd połączenia PV",
		"zh-cn": "PV错接",
	},
	10205: {
		en: "MPPT-A input overvoltage",
		de: "Eingangsüberspannung bei MPPT-A",
		ru: "Перенапряжение на входе MPPT-A",
		pt: "Sobretensão de entrada MPPT-A",
		nl: "Overspanning MPPT-A-ingang",
		fr: "Surtension de l’entrée MPPT-A",
		it: "Sovratensione ingresso MPPT-A",
		es: "Sobretensión de entrada MPPT-A",
		pl: "Nadnapięcie wejścia MPPT-A",
		"zh-cn": "MPPT-A 输入过压",
	},
	10206: {
		en: "MPPT-B input overvoltage",
		de: "Eingangsüberspannung bei MPPT-B",
		ru: "Перенапряжение на входе MPPT-B",
		pt: "Sobretensão de entrada MPPT-B",
		nl: "Overspanning MPPT-B-ingang",
		fr: "Surtension de l’entrée MPPT-B",
		it: "Sovratensione ingresso MPPT-B",
		es: "Sobretensión de entrada MPPT-B",
		pl: "Nadnapięcie wejścia MPPT-B",
		"zh-cn": "MPPT-B 输入过压",
	},
	10207: {
		en: "MPPT-A input undervoltage",
		de: "Eingangsunterspannung bei MPPT-A",
		ru: "Пониженное напряжение на входе MPPT-A",
		pt: "Subtensão de entrada MPPT-A",
		nl: "Onderspanning MPPT-A-ingang",
		fr: "Sous-tension de l’entrée MPPT-A",
		it: "Sottotensione ingresso MPPT-A",
		es: "Subtensión de entrada MPPT-A",
		pl: "Podnapięcie wejścia MPPT-A",
		"zh-cn": "MPPT-A 输入欠压",
	},
	10208: {
		en: "MPPT-B input undervoltage",
		de: "Eingangsunterspannung bei MPPT-B",
		ru: "Пониженное напряжение на входе MPPT-B",
		pt: "Subtensão de entrada MPPT-B",
		nl: "Onderspanning MPPT-B-ingang",
		fr: "Sous-tension de l’entrée MPPT-B",
		it: "Sottotensione ingresso MPPT-B",
		es: "Subtensión de entrada MPPT-B",
		pl: "Podnapięcie wejścia MPPT-B",
		"zh-cn": "MPPT-B 输入欠压",
	},
	10209: {
		en: "PV1 no input",
		de: "PV1 ohne Eingang",
		ru: "Отсутствует напряжение на входе ФЭ панели 1",
		pt: "Sem entrada FV1",
		nl: "Geen invoer voor PV1",
		fr: "Aucune entrée PV1",
		it: "Nessun ingresso FV1",
		es: "Sin entrada en el puerto FV1",
		pl: "Brak wejścia PV1",
		"zh-cn": "PV1端口无输入",
	},
	10210: {
		en: "PV2 no input",
		de: "PV2 ohne Eingang",
		ru: "Отсутствует напряжение на входе ФЭ панели 2",
		pt: "Sem entrada FV2",
		nl: "Geen invoer voor PV2",
		fr: "Aucune entrée PV2",
		it: "Nessun ingresso FV2",
		es: "Sin entrada en el puerto FV2",
		pl: "Brak wejścia PV2",
		"zh-cn": "PV2端口无输入",
	},
	10211: {
		en: "PV3 no input",
		de: "PV3 ohne Eingang",
		ru: "Отсутствует напряжение на входе ФЭ панели 3",
		pt: "Sem entrada FV3",
		nl: "Geen invoer voor PV3",
		fr: "Aucune entrée PV3",
		it: "Nessun ingresso FV3",
		es: "Sin entrada en el puerto FV3",
		pl: "Brak wejścia PV3",
		"zh-cn": "PV3端口无输入",
	},
	10212: {
		en: "PV4 no input",
		de: "PV4 ohne Eingang",
		ru: "Отсутствует напряжение на входе ФЭ панели 4",
		pt: "Sem entrada FV4",
		nl: "Geen invoer voor PV4",
		fr: "Aucune entrée PV4",
		it: "Nessun ingresso FV4",
		es: "Sin entrada en el puerto FV4",
		pl: "Brak wejścia PV4",
		"zh-cn": "PV4端口无输入",
	},
	10213: {
		en: "PV1 & PV2 abnormal wiring",
		de: "Verdrahtungsfehler bei PV1 und PV2",
		ru: "Неисправность проводки ФЭ панелей 1 и 2",
		pt: "Cabeamento anormal FV1 e FV2",
		nl: "Abnormale bedrading PV1 en PV2",
		fr: "Câblage anormal PV1 & PV2",
		it: "Cablaggio anomalo FV1 e FV2",
		es: "Cableado anormal de FV1 y FV2",
		pl: "Nieprawidłowe okablowanie PV1 i PV2",
		"zh-cn": "PV-1&PV-2端口接线异常",
	},
	10214: {
		en: "PV3 & PV4 abnormal wiring",
		de: "Verdrahtungsfehler bei PV3 und PV4",
		ru: "Неисправность проводки ФЭ панелей 3 и 4",
		pt: "Cabeamento anormal FV3 e FV4",
		nl: "Abnormale bedrading PV3 en PV4",
		fr: "Câblage anormal PV3 & PV4",
		it: "Cablaggio anomalo FV3 e FV4",
		es: "Cableado anormal de FV3 y FV4",
		pl: "Nieprawidłowe okablowanie PV3 i PV4",
		"zh-cn": "PV-3&PV-4端口接线异常",
	},
	10215: {
		en: "MPPT-C input overvoltage",
		de: "Eingangsüberspannung bei MPPT-C",
		ru: "Перенапряжение на входе MPPT-C",
		pt: "Sobretensão de entrada MPPT-C",
		nl: "Overspanning MPPT-C-ingang",
		fr: "Surtension de l’entrée MPPT-C",
		it: "Sovratensione ingresso MPPT-C",
		es: "Sobretensión de entrada MPPT-C",
		pl: "Nadnapięcie wejścia MPPT-C",
		"zh-cn": "MPPT-C 输入过压",
	},
	10216: {
		en: "MPPT-C input undervoltage",
		de: "Eingangsunterspannung bei MPPT-C",
		ru: "Пониженное напряжение на входе MPPT-C",
		pt: "Subtensão de entrada MPPT-C",
		nl: "Onderspanning MPPT-C-ingang",
		fr: "Sous-tension de l’entrée MPPT-C",
		it: "Sottotensione ingresso MPPT-C",
		es: "Subtensión de entrada MPPT-C",
		pl: "Podnapięcie wejścia MPPT-C",
		"zh-cn": "MPPT-C 输入欠压",
	},
	10217: {
		en: "PV5 no input",
		de: "PV5 ohne Eingang",
		ru: "Отсутствует напряжение на входе ФЭ панели 5",
		pt: "Sem entrada FV5",
		nl: "Geen invoer voor PV5",
		fr: "Aucune entrée PV5",
		it: "Nessun ingresso FV5",
		es: "Sin entrada en el puerto FV5",
		pl: "Brak wejścia PV5",
		"zh-cn": "PV5端口无输入",
	},
	10218: {
		en: "PV6 no input",
		de: "PV6 ohne Eingang",
		ru: "Отсутствует напряжение на входе ФЭ панели 6",
		pt: "Sem entrada FV6",
		nl: "Geen invoer voor PV6",
		fr: "Aucune entrée PV6",
		it: "Nessun ingresso FV6",
		es: "Sin entrada en el puerto FV6",
		pl: "Brak wejścia PV6",
		"zh-cn": "PV6端口无输入",
	},
	10219: {
		en: "PV5 & PV6 abnormal wiring",
		de: "Verdrahtungsfehler bei PV5 und PV6",
		ru: "Неисправность проводки ФЭ панелей 5 и 6",
		pt: "Cabeamento anormal FV5 e FV6",
		nl: "Abnormale bedrading PV5 en PV6",
		fr: "Câblage anormal PV5 & PV6",
		it: "Cablaggio anomalo FV5 e FV6",
		es: "Cableado anormal de FV5 y FV6",
		pl: "Nieprawidłowe okablowanie PV5 i PV6",
		"zh-cn": "PV-5&PV-6端口接线异常",
	},
	10220: {
		en: "MPPT-D input overvoltage",
		de: "Eingangsüberspannung bei MPPT-D",
		ru: "Перенапряжение на входе MPPT-D",
		pt: "Sobretensão de entrada MPPT-D",
		nl: "MPPT-D ingangsoverspanning",
		fr: "Surtension d’entrée MPPT-D",
		it: "Sovratensione ingresso MPPT-D",
		es: "Sobretensión de entrada MPPT-D",
		pl: "Przepięcie wejścia MPPT-D",
		"zh-cn": "MPPT-D 输入过压",
	},
	10221: {
		en: "MPPT-D input undervoltage",
		de: "Eingangsunterspannung bei MPPT-D",
		ru: "Пониженное напряжение на входе MPPT-D",
		pt: "Subtensão de entrada MPPT-D",
		nl: "MPPT-D ingangsonderspanning",
		fr: "Sous-tension d’entrée MPPT-D",
		it: "Sottotensione ingresso MPPT- D",
		es: "Subtensión de entrada MPPT- D",
		pl: "Podnapięcie wejścia MPPT-D",
		"zh-cn": "MPPT-D 输入欠压",
	},
	10225: {
		en: "BoostA overvoltage protection failure",
		de: "Fehler beim BOOSTA-Überspannungsschutz",
		ru: "Неисправность защиты от перенапряжения BOOSTA",
		pt: "Falha na proteção contra sobretensão em BOOSTA",
		nl: "BOOSTA overspanningsbeveiligingsstoring",
		fr: "Anomalie de la protection contre les surtensions BOOSTA",
		it: "Errore protezione da sovratensione BOOSTA",
		es: "Falla de protección contra sobretensión BOOSTA",
		pl: "Błąd zabezpieczenia przepięciowego BOOSTA",
		"zh-cn": "BOOSTA过压保护失效",
	},
	10226: {
		en: "BoostB overvoltage protection failure",
		de: "Fehler beim BOOSTB-Überspannungsschutz",
		ru: "Неисправность защиты от перенапряжения BOOSTB",
		pt: "Falha na proteção contra sobretensão em BOOSTB",
		nl: "BOOSTB overspanningsbeveiligingsstoring",
		fr: "Anomalie de la protection contre les surtensions BOOSTB",
		it: "Errore protezione da sovratensione BOOSTB",
		es: "Falla de protección contra sobretensión BOOSTB",
		pl: "Błąd zabezpieczenia przepięciowego BOOSTB",
		"zh-cn": "BOOSTB过压保护失效",
	},
	10227: {
		en: "BoostC overvoltage protection failure",
		de: "Fehler beim BOOSTC-Überspannungsschutz",
		ru: "Неисправность защиты от перенапряжения BOOSTC",
		pt: "Falha na proteção contra sobretensão em BOOSTC",
		nl: "BOOSTC overspanningsbeveiligingsstoring",
		fr: "Anomalie de la protection contre les surtensions BOOSTC",
		it: "Errore protezione da sovratensione BOOSTC",
		es: "Falla de protección contra sobretensión BOOSTC",
		pl: "Błąd zabezpieczenia przepięciowego BOOSTC",
		"zh-cn": "BOOSTC过压保护失效",
	},
	10228: {
		en: "BoostD overvoltage protection failure",
		de: "Fehler beim BOOSTD-Überspannungsschutz",
		ru: "Неисправность защиты от перенапряжения BOOSTD",
		pt: "Falha na proteção contra sobretensão em BOOSTD",
		nl: "BOOSTD overspanningsbeveiligingsstoring",
		fr: "Anomalie de la protection contre les surtensions BOOSTD",
		it: "Errore protezione da sovratensione BOOSTD",
		es: "Falla de protección contra sobretensión BOOSTD",
		pl: "Błąd zabezpieczenia przepięciowego BOOSTD",
		"zh-cn": "BOOSTD过压保护失效",
	},
	10229: {
		en: "Bus overvoltage protection failure",
		de: "Störung des Bus-Überspannungsschutzes",
		ru: "Неисправность защиты от перенапряжения шины",
		pt: "Falha na proteção contra sobretensão de barramento",
		nl: "Storing overspanningsbeveiliging bus",
		fr: "Anomalie de la protection anti-surtension du bus",
		it: "Errore protezione da sovratensione bus",
		es: "Falla de protección contra sobretensión del bus",
		pl: "Błąd zabezpieczenia nadnapięciowego magistrali",
		"zh-cn": "母线过压保护失效",
	},
	10230: {
		en: "Bus undervoltage protection failure",
		de: "Störung des Bus-Unterspannungsschutzes",
		ru: "Неисправность защиты от пониженного напряжения шины",
		pt: "Falha na proteção contra subtensão de barramento",
		nl: "Storing onderspanningsbeveiliging bus",
		fr: "Anomalie de la protection anti-sous-tension du bus",
		it: "Errore protezione da sottotensione bus",
		es: "Falla de protección contra subtensión del bus",
		pl: "Błąd zabezpieczenia podnapięcia magistrali",
		"zh-cn": "母线欠压保护失效",
	},
	10231: {
		en: "PV1 Arcing Fault",
		de: "PV1 Störlichtbogen",
		ru: "Дуговое замыкание ФЭ панели 1",
		pt: "Falha de arco PV1",
		nl: "PV1 Vlamboogstoring",
		fr: "PV1 Défaut d’arc",
		it: "Guasto causato da un arco elettrico FV1",
		es: "Falla de arco FV1",
		pl: "Usterka łuku elektrycznego PV1",
		"zh-cn": "PV1拉弧故障",
	},
	10232: {
		en: "PV2 Arcing Fault",
		de: "PV2 Störlichtbogen",
		ru: "Дуговое замыкание ФЭ панели 2",
		pt: "Falha de arco PV2",
		nl: "PV2 Vlamboogstoring",
		fr: "PV2 Défaut d’arc",
		it: "Guasto causato da un arco elettrico FV2",
		es: "Falla de arco FV2",
		pl: "Usterka łuku elektrycznego PV2",
		"zh-cn": "PV2拉弧故障",
	},
	10233: {
		en: "PV3 Arcing Fault",
		de: "PV3 Störlichtbogen",
		ru: "Дуговое замыкание ФЭ панели 3",
		pt: "Falha de arco PV3",
		nl: "PV3 Vlamboogstoring",
		fr: "PV3 Défaut d’arc",
		it: "Guasto causato da un arco elettrico FV3",
		es: "Falla de arco FV3",
		pl: "Usterka łuku elektrycznego PV3",
		"zh-cn": "PV3拉弧故障",
	},
	10234: {
		en: "PV4 Arcing Fault",
		de: "PV4 Störlichtbogen",
		ru: "Дуговое замыкание ФЭ панели 4",
		pt: "Falha de arco PV4",
		nl: "PV4 Vlamboogstoring",
		fr: "PV4 Défaut d’arc",
		it: "Guasto causato da un arco elettrico FV4",
		es: "Falla de arco FV4",
		pl: "Usterka łuku elektrycznego PV4",
		"zh-cn": "PV4拉弧故障",
	},
	10235: {
		en: "Abnormal Arcing Self-checking Circuit",
		de: "Anormaler Lichtbogen-Selbsttestkreis",
		ru: "Неисправность контура самодиагностики из-за дугового замыкания",
		pt: "Circuito da autoverificação de arco anormal",
		nl: "Abnormale vlamboogvorming zelfcontrolerende groep",
		fr: "Circuit d’auto-vérification de l’arc électrique anormal",
		it: "Anomalia circuito di autoverifica arco elettrico",
		es: "Circuito de autocomprobación de arco anormal",
		pl: "Nieprawidłowy obwód samosprawdzania łuku",
		"zh-cn": "拉弧自检电路异常",
	},
	10236: {
		en: "Abnormal Inverter Driver Circuit",
		de: "Anormaler Wechselrichter-Treiberkreis",
		ru: "Неисправность контура привода инвертора",
		pt: "Circuito do driver do inversor anormal",
		nl: "Abnormale omvormerdrivergroep",
		fr: "Circuit de commande de l’onduleur anormal",
		it: "Anomalia circuito di azionamento inverter",
		es: "Circuito de controlador de inversor anormal",
		pl: "Nieprawidłowy obwód sterownika falownika",
		"zh-cn": "逆变驱动电路异常",
	},
	10301: {
		en: "Hardware Error Code 301",
		de: "Hardwarefehlercode 301",
		ru: "Код аппаратной ошибки 301",
		pt: "Código de erro de hardware 301",
		nl: "Hardwarefoutcode 301",
		fr: "Code d’erreur matériel 301",
		it: "Errore hardware Codice 301",
		es: "Código de Error de Hardware 301",
		pl: "Kod błędu sprzętowego 301",
		"zh-cn": "硬件错误码301",
	},
	10302: {
		en: "Hardware Error Code 302",
		de: "Hardwarefehlercode 302",
		ru: "Код аппаратной ошибки 302",
		pt: "Código de erro de hardware 302",
		nl: "Hardwarefoutcode 302",
		fr: "Code d’erreur matériel 302",
		it: "Errore hardware Codice 302",
		es: "Código de Error de Hardware 302",
		pl: "Kod błędu sprzętowego 302",
		"zh-cn": "硬件错误码302",
	},
	10303: {
		en: "Hardware Error Code 303",
		de: "Hardwarefehlercode 303",
		ru: "Код аппаратной ошибки 303",
		pt: "Código de erro de hardware 303",
		nl: "Hardwarefoutcode 303",
		fr: "Code d’erreur matériel 303",
		it: "Errore hardware Codice 303",
		es: "Código de Error de Hardware 303",
		pl: "Kod błędu sprzętowego 303",
		"zh-cn": "硬件错误码303",
	},
	10304: {
		en: "Hardware Error Code 304",
		de: "Hardwarefehlercode 304",
		ru: "Код аппаратной ошибки 304",
		pt: "Código de erro de hardware 304",
		nl: "Hardwarefoutcode 304",
		fr: "Code d’erreur matériel 304",
		it: "Errore hardware Codice 304",
		es: "Código de Error de Hardware 304",
		pl: "Kod błędu sprzętowego 304",
		"zh-cn": "硬件错误码304",
	},
	10305: {
		en: "Hardware Error Code 305",
		de: "Hardwarefehlercode 305",
		ru: "Код аппаратной ошибки 305",
		pt: "Código de erro de hardware 305",
		nl: "Hardwarefoutcode 305",
		fr: "Code d’erreur matériel 305",
		it: "Errore hardware Codice 305",
		es: "Código de Error de Hardware 305",
		pl: "Kod błędu sprzętowego 305",
		"zh-cn": "硬件错误码305",
	},
	10306: {
		en: "Hardware Error Code 306",
		de: "Hardwarefehlercode 306",
		ru: "Код аппаратной ошибки 306",
		pt: "Código de erro de hardware 306",
		nl: "Hardwarefoutcode 306",
		fr: "Code d’erreur matériel 306",
		it: "Errore hardware Codice 306",
		es: "Código de Error de Hardware 306",
		pl: "Kod błędu sprzętowego 306",
		"zh-cn": "硬件错误码306",
	},
	10307: {
		en: "Hardware Error Code 307",
		de: "Hardwarefehlercode 307",
		ru: "Код аппаратной ошибки 307",
		pt: "Código de erro de hardware 307",
		nl: "Hardwarefoutcode 307",
		fr: "Code d’erreur matériel 307",
		it: "Errore hardware Codice 307",
		es: "Código de Error de Hardware 307",
		pl: "Kod błędu sprzętowego 307",
		"zh-cn": "硬件错误码307",
	},
	10308: {
		en: "Hardware Error Code 308",
		de: "Hardwarefehlercode 308",
		ru: "Код аппаратной ошибки 308",
		pt: "Código de erro de hardware 308",
		nl: "Hardwarefoutcode 308",
		fr: "Code d’erreur matériel 308",
		it: "Errore hardware Codice 308",
		es: "Código de Error de Hardware 308",
		pl: "Kod błędu sprzętowego 308",
		"zh-cn": "硬件错误码308",
	},
	10309: {
		en: "Hardware Error Code 309",
		de: "Hardwarefehlercode 309",
		ru: "Код аппаратной ошибки 309",
		pt: "Código de erro de hardware 309",
		nl: "Hardwarefoutcode 309",
		fr: "Code d’erreur matériel 309",
		it: "Errore hardware Codice 309",
		es: "Código de Error de Hardware 309",
		pl: "Kod błędu sprzętowego 309",
		"zh-cn": "硬件错误码309",
	},
	10310: {
		en: "Hardware Error Code 310",
		de: "Hardwarefehlercode 310",
		ru: "Код аппаратной ошибки 310",
		pt: "Código de erro de hardware 310",
		nl: "Hardwarefoutcode 310",
		fr: "Code d’erreur matériel 310",
		it: "Errore hardware Codice 310",
		es: "Código de Error de Hardware 310",
		pl: "Kod błędu sprzętowego 310",
		"zh-cn": "硬件错误码310",
	},
	10311: {
		en: "Hardware Error Code 311",
		de: "Hardwarefehlercode 311",
		ru: "Код аппаратной ошибки 311",
		pt: "Código de erro de hardware 311",
		nl: "Hardwarefoutcode 311",
		fr: "Code d’erreur matériel 311",
		it: "Errore hardware Codice 311",
		es: "Código de Error de Hardware 311",
		pl: "Kod błędu sprzętowego 311",
		"zh-cn": "硬件错误码311",
	},
	10315: {
		en: "BOOSTA internal short circuit failure",
		de: "BOOSTA interner Kurzschlussfehler",
		ru: "Внутреннее короткое замыкание BOOSTA",
		pt: "Falha de curto-circuito interno em BOOSTA",
		nl: "BOOSTA interne kortsluitingsstoring",
		fr: "Anomalie de la protection contre les courts-circuits internes BOOSTA",
		it: "Errore cortocircuito interno BOOSTA",
		es: "Falla de cortocircuito interno de BOOSTA",
		pl: "Błąd zwarcia wewnętrznego BOOSTA",
		"zh-cn": "BOOSTA内部短路失效",
	},
	10316: {
		en: "BOOSTB internal short circuit failure",
		de: "BOOSTB interner Kurzschlussfehler",
		ru: "Внутреннее короткое замыкание BOOSTB",
		pt: "Falha de curto-circuito interno em BOOSTB",
		nl: "BOOSTB interne kortsluitingsstoring",
		fr: "Anomalie de la protection contre les courts-circuits internes BOOSTB",
		it: "Errore cortocircuito interno BOOSTB",
		es: "Falla de cortocircuito interno de BOOSTB",
		pl: "Błąd zwarcia wewnętrznego BOOSTB",
		"zh-cn": "BOOSTB内部短路失效",
	},
	10317: {
		en: "BOOSTC internal short circuit failure",
		de: "BOOSTC interner Kurzschlussfehler",
		ru: "Внутреннее короткое замыкание BOOSTC",
		pt: "Falha de curto-circuito interno em BOOSTC",
		nl: "BOOSTC interne kortsluitingsstoring",
		fr: "Anomalie de la protection contre les courts-circuits internes BOOSTC",
		it: "Errore cortocircuito interno BOOSTC",
		es: "Falla de cortocircuito interno de BOOSTC",
		pl: "Błąd zwarcia wewnętrznego BOOSTC",
		"zh-cn": "BOOSTC内部短路失效",
	},
	10318: {
		en: "BOOSTD internal short circuit failure",
		de: "BOOSTD interner Kurzschlussfehler",
		ru: "Внутреннее короткое замыкание BOOSTD",
		pt: "Falha de curto-circuito interno em BOOSTD",
		nl: "BOOSTD interne kortsluitingsstoring",
		fr: "Anomalie de la protection contre les courts-circuits internes BOOSTD",
		it: "Errore cortocircuito interno BOOSTD",
		es: "Falla de cortocircuito interno de BOOSTD",
		pl: "Błąd zwarcia wewnętrznego BOOSTD",
		"zh-cn": "BOOSTD内部短路失效",
	},
	10319: {
		en: "BoostA Overcurrent Protection Failure",
		de: "Ausfall des BOOSTA-Überstromschutzes",
		ru: "Неисправность защиты от перегрузки по току BOOSTA",
		pt: "Falha na proteção contra sobrecorrente em BOOSTA",
		nl: "BOOSTA overstroombeveiligingsstoring",
		fr: "Anomalie de la protection contre les surintensités BOOSTA",
		it: "Errore protezione dalle sovracorrenti BOOSTA",
		es: "Falla de protección contra sobrecorriente BOOSTA",
		pl: "Błąd zabezpieczenia przetężeniowego BOOSTA",
		"zh-cn": "BOOSTA过流保护失效",
	},
	10320: {
		en: "BoostB Overcurrent Protection Failure",
		de: "Ausfall des BOOSTB-Überstromschutzes",
		ru: "Неисправность защиты от перегрузки по току BOOSTB",
		pt: "Falha na proteção contra sobrecorrente em BOOSTB",
		nl: "BOOSTB overstroombeveiligingsstoring",
		fr: "Anomalie de la protection contre les surintensités BOOSTB",
		it: "Errore protezione dalle sovracorrenti BOOSTB",
		es: "Falla de protección contra sobrecorriente BOOSTB",
		pl: "Błąd zabezpieczenia przetężeniowego BOOSTB",
		"zh-cn": "BOOSTB过流保护失效",
	},
	10321: {
		en: "BoostC Overcurrent Protection Failure",
		de: "Ausfall des BOOSTC-Überstromschutzes",
		ru: "Неисправность защиты от перегрузки по току BOOSTC",
		pt: "Falha na proteção contra sobrecorrente em BOOSTC",
		nl: "BOOSTC overstroombeveiligingsstoring",
		fr: "Anomalie de la protection contre les surintensités BOOSTC",
		it: "Errore protezione dalle sovracorrenti BOOSTC",
		es: "Falla de protección contra sobrecorriente BOOSTC",
		pl: "Błąd zabezpieczenia przetężeniowego BOOSTC",
		"zh-cn": "BOOSTC过流保护失效",
	},
	10322: {
		en: "BoostD Overcurrent Protection Failure",
		de: "Ausfall des BOOSTD-Überstromschutzes",
		ru: "Неисправность защиты от перегрузки по току BOOSTD",
		pt: "Falha na proteção contra sobrecorrente em BOOSTD",
		nl: "BOOSTD overstroombeveiligingsstoring",
		fr: "Anomalie de la protection contre les surintensités BOOSTD",
		it: "Errore protezione dalle sovracorrenti BOOSTD",
		es: "Falla de protección contra sobrecorriente BOOSTD",
		pl: "Błąd zabezpieczenia przetężeniowego BOOSTD",
		"zh-cn": "BOOSTD过流保护失效",
	},
	10323: {
		en: "INVA overcurrent protection failure",
		de: "INVA-Überstromschutzfehler",
		ru: "Неисправность защиты от перегрузки по току INVA",
		pt: "Falha na proteção contra sobrecorrente em INVA",
		nl: "INVA-overstroombeveiligingsstoring",
		fr: "Anomalie de la protection contre les surintensités INVA",
		it: "Errore protezione dalle sovracorrenti INVA",
		es: "Falla de protección contra sobrecorriente INVA",
		pl: "Błąd zabezpieczenia przetężeniowego INVA",
		"zh-cn": "INVA过流保护失效",
	},
	10324: {
		en: "INVB overcurrent protection failure",
		de: "INVB-Überstromschutzfehler",
		ru: "Неисправность защиты от перегрузки по току INVB",
		pt: "Falha na proteção contra sobrecorrente em INVB",
		nl: "INVB-overstroombeveiligingsstoring",
		fr: "Anomalie de la protection contre les surintensités INVB",
		it: "Errore protezione dalle sovracorrenti INVB",
		es: "Falla de protección contra sobrecorriente INVB",
		pl: "Błąd zabezpieczenia przetężeniowego INVB",
		"zh-cn": "INVB过流保护失效",
	},
	10325: {
		en: "INVC overcurrent protection failure",
		de: "INVC-Überstromschutzfehler",
		ru: "Неисправность защиты от перегрузки по току INVC",
		pt: "Falha na proteção contra sobrecorrente em INVC",
		nl: "INVC-overstroombeveiligingsstoring",
		fr: "Anomalie de la protection contre les surintensités INVC",
		it: "Errore protezione dalle sovracorrenti INVC",
		es: "Falla de protección contra sobrecorriente INVC",
		pl: "Błąd zabezpieczenia przetężeniowego INVC",
		"zh-cn": "INVC过流保护失效",
	},
	10326: {
		en: "Arcing Lock-Up",
		de: "Sperrlichtbogen",
		ru: "Блокировка из-за дугового замыкания",
		pt: "Bloqueio de arco",
		nl: "Blokkering vlamboogvorming",
		fr: "Verrouillage de l’arc électrique",
		it: "Blocco causato da un arco elettrico",
		es: "Bloqueo de arco",
		pl: "Blokada łuku",
		"zh-cn": "拉弧锁死",
	},
};
