interface ChannelDefinition {
	id: string;
	name: ioBroker.StringOrTranslated;
	source?: "local" | "cloud";
}

interface StateDefinition {
	id: string;
	name: ioBroker.StringOrTranslated;
	type: ioBroker.CommonType;
	role: string;
	unit?: string;
	write?: boolean;
	min?: number;
	max?: number;
	states?: Record<number, string>;
	source?: "local" | "cloud";
}

const channels: ChannelDefinition[] = [
	{ id: "grid", name: { en: "Grid output", de: "Netzeinspeisung" } },
	// PV channels (pv0, pv1, pv2, pv3) are created dynamically based on pvNumber
	{ id: "inverter", name: { en: "Inverter", de: "Wechselrichter" } },
	{ id: "dtu", name: { en: "DTU", de: "DTU" }, source: "local" },
	{ id: "info", name: { en: "Adapter info", de: "Adapter-Info" } },
	{ id: "alarms", name: { en: "Alarms & warnings", de: "Alarme & Warnungen" }, source: "local" },
	{ id: "config", name: { en: "DTU configuration", de: "DTU-Konfiguration" }, source: "local" },
	// meter channel is created dynamically when meter data is first received
];

const states: StateDefinition[] = [
	// === Grid (from SGSMO / Cloud) ===
	{
		id: "grid.power",
		name: { en: "Grid power", de: "Netzleistung" },
		type: "number",
		role: "value.power",
		unit: "W",
		source: "local",
	},
	{
		id: "grid.voltage",
		name: { en: "Grid voltage", de: "Netzspannung" },
		type: "number",
		role: "value.voltage",
		unit: "V",
		source: "local",
	},
	{
		id: "grid.current",
		name: { en: "Grid current", de: "Netzstrom" },
		type: "number",
		role: "value.current",
		unit: "A",
		source: "local",
	},
	{
		id: "grid.frequency",
		name: { en: "Grid frequency", de: "Netzfrequenz" },
		type: "number",
		role: "value",
		unit: "Hz",
		source: "local",
	},
	{
		id: "grid.reactivePower",
		name: { en: "Reactive power", de: "Blindleistung" },
		type: "number",
		role: "value",
		unit: "var",
		source: "local",
	},
	{
		id: "grid.powerFactor",
		name: { en: "Power factor", de: "Leistungsfaktor" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "grid.dailyEnergy",
		name: { en: "Daily energy", de: "Tagesenergie" },
		type: "number",
		role: "value.energy",
		unit: "kWh",
	},
	{
		id: "grid.totalEnergy",
		name: { en: "Total energy (AC)", de: "Gesamtenergie (AC)" },
		type: "number",
		role: "value.energy",
		unit: "kWh",
		source: "cloud",
	},

	// PV states are created dynamically based on pvNumber from DTU info response
	// (see createPvStates() in main.ts)

	// === Inverter ===
	{
		id: "inverter.serialNumber",
		name: { en: "Serial number", de: "Seriennummer" },
		type: "string",
		role: "text",
		unit: "",
	},
	{
		id: "inverter.hwVersion",
		name: { en: "Hardware version", de: "Hardware-Version" },
		type: "string",
		role: "text",
		unit: "",
	},
	{
		id: "inverter.swVersion",
		name: { en: "Software version", de: "Software-Version" },
		type: "string",
		role: "text",
		unit: "",
	},
	{
		id: "inverter.temperature",
		name: { en: "Temperature", de: "Temperatur" },
		type: "number",
		role: "value.temperature",
		unit: "\u00b0C",
		source: "local",
	},
	{
		id: "inverter.powerLimit",
		name: { en: "Power limit", de: "Leistungslimit" },
		type: "number",
		role: "level",
		unit: "%",
		write: true,
		min: 0,
		max: 100,
		source: "local",
	},
	{
		id: "inverter.activePowerLimit",
		name: { en: "Active power limit (live)", de: "Aktives Leistungslimit (live)" },
		type: "number",
		role: "value",
		unit: "%",
		source: "local",
	},
	{
		id: "inverter.active",
		name: { en: "Inverter active", de: "Wechselrichter aktiv" },
		type: "boolean",
		role: "switch",
		write: true,
		source: "local",
	},
	{
		id: "inverter.reboot",
		name: { en: "Reboot inverter", de: "Wechselrichter neustarten" },
		type: "boolean",
		role: "button",
		write: true,
		source: "local",
	},
	{
		id: "inverter.powerFactorLimit",
		name: { en: "Power factor limit", de: "Leistungsfaktor-Limit" },
		type: "number",
		role: "level",
		unit: "",
		write: true,
		min: -1,
		max: 1,
		source: "local",
	},
	{
		id: "inverter.reactivePowerLimit",
		name: { en: "Reactive power limit", de: "Blindleistungs-Limit" },
		type: "number",
		role: "level",
		unit: "°",
		write: true,
		min: -50,
		max: 50,
		source: "local",
	},
	{
		id: "inverter.cleanWarnings",
		name: { en: "Clean warnings", de: "Warnungen löschen" },
		type: "boolean",
		role: "button",
		write: true,
		source: "local",
	},
	{
		id: "inverter.cleanGroundingFault",
		name: { en: "Clean grounding fault", de: "Erdungsfehler löschen" },
		type: "boolean",
		role: "button",
		write: true,
		source: "local",
	},
	{
		id: "inverter.lock",
		name: { en: "Lock inverter", de: "Wechselrichter sperren" },
		type: "boolean",
		role: "switch",
		write: true,
		source: "local",
	},
	{
		id: "inverter.warnCount",
		name: { en: "Active warning code", de: "Aktiver Warnungscode" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "inverter.warnMessage",
		name: { en: "Active warning message", de: "Aktive Warnungsmeldung" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "inverter.linkStatus",
		name: { en: "Link status", de: "Verbindungsstatus" },
		type: "number",
		role: "value",
		unit: "",
	},

	// === DTU ===
	{
		id: "dtu.serialNumber",
		name: { en: "Serial number", de: "Seriennummer" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "dtu.hwVersion",
		name: { en: "Hardware version", de: "Hardware-Version" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "dtu.swVersion",
		name: { en: "Software version", de: "Software-Version" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "dtu.rssi",
		name: { en: "Signal strength", de: "Signalstärke" },
		type: "number",
		role: "value",
		unit: "dBm",
		source: "local",
	},
	{
		id: "dtu.wifiVersion",
		name: { en: "WiFi version", de: "WLAN-Version" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "dtu.reboot",
		name: { en: "Reboot DTU", de: "DTU neustarten" },
		type: "boolean",
		role: "button",
		write: true,
		source: "local",
	},
	{
		id: "dtu.stepTime",
		name: { en: "Step time", de: "Schrittzeit" },
		type: "number",
		role: "value",
		unit: "s",
		source: "local",
	},
	{
		id: "dtu.rfHwVersion",
		name: { en: "RF hardware version", de: "RF Hardware-Version" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "dtu.rfSwVersion",
		name: { en: "RF software version", de: "RF Software-Version" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "dtu.accessModel",
		name: { en: "Network access mode", de: "Netzwerk-Zugangsart" },
		type: "number",
		role: "value",
		unit: "",
		states: { 0: "GPRS", 1: "WiFi", 2: "Ethernet" },
		source: "local",
	},
	{
		id: "dtu.communicationTime",
		name: { en: "Last communication", de: "Letzte Kommunikation" },
		type: "number",
		role: "value.time",
		unit: "",
		source: "local",
	},
	{
		id: "dtu.connState",
		name: { en: "DTU error code", de: "DTU Fehlercode" },
		type: "number",
		role: "value",
		unit: "",
		states: { 0: "OK" },
		source: "local",
	},
	{
		id: "dtu.mode485",
		name: { en: "RS485 mode", de: "RS485 Modus" },
		type: "number",
		role: "value",
		unit: "",
		states: { 0: "Reflux/Auto", 1: "Remote Control" },
		source: "local",
	},
	{
		id: "dtu.sub1gFrequencyBand",
		name: { en: "Sub-1G frequency band", de: "Sub-1G Frequenzband" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},

	// === Info (adapter-level) ===
	{
		id: "info.connection",
		name: { en: "Connected", de: "Verbunden" },
		type: "boolean",
		role: "indicator.connected",
		unit: "",
		source: "local",
	},
	{
		id: "info.lastResponse",
		name: { en: "Last response time", de: "Letzte Antwortzeit" },
		type: "number",
		role: "value.time",
		unit: "",
		source: "local",
	},

	// === Alarms ===
	{
		id: "alarms.count",
		name: { en: "Alarm count", de: "Alarmanzahl" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "alarms.activeCount",
		name: { en: "Active alarm count", de: "Aktive Alarme" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "alarms.hasActive",
		name: { en: "Has active alarms", de: "Aktive Alarme vorhanden" },
		type: "boolean",
		role: "indicator.alarm",
		unit: "",
		source: "local",
	},
	{
		id: "alarms.lastCode",
		name: { en: "Last alarm code", de: "Letzter Alarmcode" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "alarms.lastMessage",
		name: { en: "Last alarm message", de: "Letzte Alarmmeldung" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "alarms.lastStartTime",
		name: { en: "Last alarm start time", de: "Letzter Alarm Startzeit" },
		type: "number",
		role: "value.time",
		unit: "",
		source: "local",
	},
	{
		id: "alarms.lastEndTime",
		name: { en: "Last alarm end time", de: "Letzter Alarm Endzeit" },
		type: "number",
		role: "value.time",
		unit: "",
		source: "local",
	},
	{
		id: "alarms.lastData1",
		name: { en: "Last alarm data 1 (raw sensor)", de: "Letzter Alarm Daten 1 (Rohwert)" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "alarms.lastData2",
		name: { en: "Last alarm data 2 (raw sensor)", de: "Letzter Alarm Daten 2 (Rohwert)" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "alarms.json",
		name: { en: "All alarms (JSON)", de: "Alle Alarme (JSON)" },
		type: "string",
		role: "json",
		unit: "",
		source: "local",
	},

	// === Config (from GetConfig) ===
	{
		id: "config.serverDomain",
		name: { en: "Cloud server domain", de: "Cloud-Server Domain" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "config.serverPort",
		name: { en: "Cloud server port", de: "Cloud-Server Port" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "config.serverSendTime",
		name: { en: "Cloud send interval", de: "Cloud-Sendeintervall" },
		type: "number",
		role: "level",
		unit: "min",
		write: true,
		source: "local",
	},
	{
		id: "config.wifiSsid",
		name: { en: "WiFi SSID", de: "WLAN SSID" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "config.wifiRssi",
		name: { en: "WiFi RSSI", de: "WLAN Signalstärke" },
		type: "number",
		role: "value",
		unit: "dBm",
		source: "local",
	},
	{
		id: "config.zeroExportEnable",
		name: { en: "Zero export enabled", de: "Nulleinspeisung aktiviert" },
		type: "boolean",
		role: "switch.enable",
		unit: "",
		write: true,
		source: "local",
	},
	{
		id: "config.zeroExport433Addr",
		name: { en: "Zero export 433MHz address", de: "Nulleinspeisung 433MHz Adresse" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "config.meterKind",
		name: { en: "Meter type", de: "Zählertyp" },
		type: "string",
		role: "text",
		states: {
			0: "No Meter",
			1: "Single-phase",
			2: "Two-phase",
			3: "Three-phase",
			5: "CT (G3)",
			6: "Meter 1S/1T (G3)",
			7: "Meter 2S/2T (G3)",
		},
		unit: "",
		source: "local",
	},
	{
		id: "config.meterInterface",
		name: { en: "Meter interface", de: "Zähler-Schnittstelle" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "config.netDhcpSwitch",
		name: { en: "DHCP enabled", de: "DHCP aktiviert" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "config.dtuApSsid",
		name: { en: "DTU AP SSID", de: "DTU AP SSID" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "config.netmodeSelect",
		name: { en: "Network mode", de: "Netzwerkmodus" },
		type: "number",
		role: "value",
		unit: "",
		states: { 0: "GPRS", 1: "WiFi", 2: "Ethernet" },
		source: "local",
	},
	{
		id: "config.channelSelect",
		name: { en: "Channel select", de: "Kanalauswahl" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "config.sub1gSweepSwitch",
		name: { en: "Sub-1G sweep", de: "Sub-1G Sweep" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "config.sub1gWorkChannel",
		name: { en: "Sub-1G work channel", de: "Sub-1G Arbeitskanal" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "config.invType",
		name: { en: "Inverter type", de: "Wechselrichter-Typ" },
		type: "number",
		role: "value",
		unit: "",
		source: "local",
	},
	{
		id: "config.netIpAddress",
		name: { en: "IP address", de: "IP-Adresse" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "config.netSubnetMask",
		name: { en: "Subnet mask", de: "Subnetzmaske" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "config.netGateway",
		name: { en: "Default gateway", de: "Standard-Gateway" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "config.wifiIpAddress",
		name: { en: "WiFi IP address", de: "WLAN IP-Adresse" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "config.netMacAddress",
		name: { en: "MAC address", de: "MAC-Adresse" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},
	{
		id: "config.wifiMacAddress",
		name: { en: "WiFi MAC address", de: "WLAN MAC-Adresse" },
		type: "string",
		role: "text",
		unit: "",
		source: "local",
	},

	// === CLOUD: Station info ===
	{
		id: "info.cloudConnected",
		name: { en: "Cloud connected", de: "Cloud verbunden" },
		type: "boolean",
		role: "indicator.connected",
		unit: "",
		source: "cloud",
	},
	{
		id: "info.lastCloudUpdate",
		name: { en: "Last cloud update", de: "Letztes Cloud-Update" },
		type: "number",
		role: "value.time",
		unit: "",
		source: "cloud",
	},
	{
		id: "info.lastDataTime",
		name: { en: "Last DTU data time", de: "Letzte DTU-Datenzeit" },
		type: "number",
		role: "value.time",
		unit: "",
		source: "cloud",
	},
	{
		id: "info.stationName",
		name: { en: "Station name", de: "Anlagenname" },
		type: "string",
		role: "text",
		unit: "",
		source: "cloud",
	},
	{
		id: "info.stationId",
		name: { en: "Station ID", de: "Anlagen-ID" },
		type: "number",
		role: "value",
		unit: "",
		source: "cloud",
	},
	{
		id: "info.systemCapacity",
		name: { en: "System capacity", de: "Anlagenleistung" },
		type: "number",
		role: "value",
		unit: "kWp",
		source: "cloud",
	},
	{
		id: "info.address",
		name: { en: "Station address", de: "Anlagenstandort" },
		type: "string",
		role: "text",
		unit: "",
		source: "cloud",
	},
	{
		id: "info.latitude",
		name: { en: "Latitude", de: "Breitengrad" },
		type: "number",
		role: "value.gps.latitude",
		unit: "\u00b0",
		source: "cloud",
	},
	{
		id: "info.longitude",
		name: { en: "Longitude", de: "Längengrad" },
		type: "number",
		role: "value.gps.longitude",
		unit: "\u00b0",
		source: "cloud",
	},
	{
		id: "info.stationStatus",
		name: { en: "Station status", de: "Anlagenstatus" },
		type: "number",
		role: "value",
		unit: "",
		states: {
			0: "Offline",
			10: "Standby",
			20: "Starting",
			30: "Producing",
			40: "Producing (normal)",
			50: "Fault",
			60: "Maintenance",
		},
		source: "cloud",
	},
	{
		id: "info.installedAt",
		name: { en: "Installation date", de: "Installationsdatum" },
		type: "number",
		role: "value.time",
		unit: "",
		source: "cloud",
	},
	{
		id: "info.timezone",
		name: { en: "Timezone", de: "Zeitzone" },
		type: "string",
		role: "text",
		unit: "",
		source: "cloud",
	},
	{
		id: "inverter.model",
		name: { en: "Model", de: "Modell" },
		type: "string",
		role: "text",
		unit: "",
		source: "cloud",
	},

	// === CLOUD: Energy aggregates ===
	{
		id: "grid.monthEnergy",
		name: { en: "Month energy", de: "Monatsenergie" },
		type: "number",
		role: "value.energy",
		unit: "kWh",
		source: "cloud",
	},
	{
		id: "grid.yearEnergy",
		name: { en: "Year energy", de: "Jahresenergie" },
		type: "number",
		role: "value.energy",
		unit: "kWh",
		source: "cloud",
	},
	{
		id: "grid.co2Saved",
		name: { en: "CO2 saved", de: "CO2-Einsparung" },
		type: "number",
		role: "value",
		unit: "kg",
		source: "cloud",
	},
	{
		id: "grid.treesPlanted",
		name: { en: "Trees planted equivalent", de: "Bäume-Äquivalent" },
		type: "number",
		role: "value",
		unit: "",
		source: "cloud",
	},
	{
		id: "grid.isBalance",
		name: { en: "Zero export active", de: "Nulleinspeisung aktiv" },
		type: "boolean",
		role: "indicator",
		unit: "",
		source: "cloud",
	},
	{
		id: "grid.isReflux",
		name: { en: "Feed-in active", de: "Rückspeisung aktiv" },
		type: "boolean",
		role: "indicator",
		unit: "",
		source: "cloud",
	},
	{
		id: "grid.electricityPrice",
		name: { en: "Electricity price", de: "Strompreis" },
		type: "number",
		role: "value",
		unit: "/kWh",
		source: "cloud",
	},
	{
		id: "grid.currency",
		name: { en: "Currency", de: "Währung" },
		type: "string",
		role: "text",
		unit: "",
		source: "cloud",
	},
	{
		id: "grid.todayIncome",
		name: { en: "Today income", de: "Tagesertrag" },
		type: "number",
		role: "value",
		unit: "",
		source: "cloud",
	},
	{
		id: "grid.totalIncome",
		name: { en: "Total income", de: "Gesamtertrag" },
		type: "number",
		role: "value",
		unit: "",
		source: "cloud",
	},
];

export type { ChannelDefinition, StateDefinition };
export { channels, states };
